import { draftDatabaseTests } from "./draft-test-database.js";
import { randomUUID } from "node:crypto";
import { prisma } from "@event-platform/database";
import { canonicalHallGeometry,editorHallV3,newEventCreationDraft,newHallObject,type EventCreationDraftV2 } from "@event-platform/shared-types";
import { beforeAll,afterAll,describe,expect,it,vi } from "vitest";
import { persistSelectedSale,validateSelectedSale } from "./creation-sale.persistence.js";
import { configuredPaymentCurrencies,DevelopmentPaymentProvider } from "../booking/payment-provider.js";
import { DomainEventsService } from "../domain-events/domain-events.service.js";
import { TablesService } from "../tables/tables.service.js";
import { TicketTypesService } from "../ticket-types/ticket-types.service.js";
import { BookingService } from "../booking/booking.service.js";
import { PaymentService } from "../payments/payment.service.js";
import { CheckoutEmailService } from "../booking/checkout-email.service.js";
import { VenueService } from "../venue/venue.service.js";
import { SeatsService } from "../seats/seats.service.js";

const owner=randomUUID(),guest=randomUUID(),eventIds:string[]=[],domain=new DomainEventsService(),clock={now:()=>new Date("2030-01-01T12:00:00Z")};
const tables=new TablesService(prisma,domain,{holdTtlSeconds:600,cleanupIntervalSeconds:60},clock),types=new TicketTypesService(prisma,domain),provider=new DevelopmentPaymentProvider("http://localhost:3000"),payments=new PaymentService(prisma,provider,domain,clock),booking=new BookingService(prisma,types,tables,domain,{checkoutTtlSeconds:900,cleanupIntervalSeconds:60},clock,payments,new CheckoutEmailService({} as never)),venue=new VenueService(prisma,domain,tables);
const currencies=provider.supportedCurrencies;
async function event(){const id=randomUUID();eventIds.push(id);await prisma.event.create({data:{id,organizerId:owner,title:"Selected sale fixture",date:new Date("2031-01-01"),time:new Date("1970-01-01T20:00:00Z"),timezone:"Asia/Almaty",address:"Address",status:"draft",sourceLocale:"en"}});return id;}
function draft(mode:EventCreationDraftV2["selectedMode"]){const value=newEventCreationDraft(randomUUID(),"en");value.selectedMode=mode;value.currency="USD";value.free.capacity=1;value.free.content.en={name:"Registration"};value.paidGeneral=[{id:randomUUID(),active:true,amount:1234,capacity:4,content:{en:{name:"Adult",description:"Any guest"},kk:{name:"Ересек"}}},{id:randomUUID(),active:false,amount:99999,capacity:5,content:{en:{name:"Inactive"}}}];return value;}
async function persist(id:string,draft:EventCreationDraftV2){return prisma.$transaction(tx=>persistSelectedSale(tx,id,owner,draft,currencies),{timeout:60000});}
function hallDraft(){const value=draft("paid_seated"),tariff=randomUUID();const table={...newHallObject(randomUUID(),"table_rect",5,5),tariffId:tariff,saleMode:"whole_table" as const,name:"Table"},seat={...newHallObject(randomUUID(),"seat",5,4),tariffId:null,parentId:table.id,side:"top" as const,number:1},single={...newHallObject(randomUUID(),"seat",10,5),tariffId:tariff,number:2};value.paidSeated=editorHallV3({widthM:24,heightM:16},{version:1,objects:[table,seat,single],tariffs:[{id:tariff,name:"VIP",price:2550,color:"#6320ee",description:"Best view",localized:{en:{name:"VIP",description:"Best view"},kk:{name:"ВИП"}}}]},null,"en");return {value,table,seat,single,tariff};}
describe.runIf(draftDatabaseTests)("selected-mode canonical inventory",()=>{
  beforeAll(async()=>{await prisma.user.createMany({data:[{id:owner,role:"organizer"},{id:guest,role:"guest"}]});});
  it("materializes only selected general tickets with stable IDs and one non-KZT price",async()=>{const id=await event(),value=draft("paid_general");await persist(id,value);const inventory=await prisma.ticketType.findMany({where:{eventId:id},include:{contents:true}});expect(inventory).toHaveLength(1);expect(inventory[0]).toMatchObject({id:value.paidGeneral[0]!.id,price:1234,currency:"USD",quantityTotal:4,deposit:0,status:"active"});expect(inventory[0]!.contents).toEqual(expect.arrayContaining([expect.objectContaining({locale:"kk",name:"Ересек"})]));expect(await prisma.ticketType.findUnique({where:{id:value.free.id}})).toBeNull();await prisma.event.update({where:{id},data:{status:"published"}});expect(await booking.checkoutTickets(guest,randomUUID(),{ticketTypeId:value.paidGeneral[0]!.id,quantity:1,termsAccepted:true})).toMatchObject({amountDue:1234,currency:"USD"});});
  it("rejects unsupported production currencies and another event's stable IDs",async()=>{const id=await event(),value=draft("paid_general");expect(configuredPaymentCurrencies({NODE_ENV:"production",DEMO_MODE:false,PAYMENT_PROVIDER_NAME:"mock"})).toEqual([]);expect(configuredPaymentCurrencies({NODE_ENV:"production",PAYMENT_PROVIDER_NAME:"unconfigured"})).toEqual([]);expect(()=>validateSelectedSale(value,[{code:"KZT",exponent:2}])).toThrow();await persist(id,value);await expect(persist(await event(),value)).rejects.toMatchObject({status:409});});
  it("persists hall geometry/tariffs without price/deposit JSON and protects owned editing",async()=>{const id=await event(),h=hallDraft();h.value.paidSeated!.tariffs.push({id:randomUUID(),active:false,amount:null,content:{en:{name:"Inactive draft"}}});const result=await persist(id,h.value);expect(result).toHaveProperty("layoutId");const raw=await prisma.venueLayout.findUniqueOrThrow({where:{eventId:id}});expect(raw.layoutJson).toEqual(canonicalHallGeometry(h.value.paidSeated!));expect(JSON.stringify(raw.layoutJson)).not.toContain('"price"');expect(JSON.stringify(raw.layoutJson)).not.toContain("deposit");expect(await prisma.table.findUnique({where:{id:h.table.id}})).toMatchObject({price:2550,deposit:0,currency:"USD",saleMode:"whole_table",seats:1,tariffId:h.tariff});expect(await prisma.seat.findUnique({where:{id:h.seat.id}})).toMatchObject({ticketTypeId:null});expect(await prisma.ticketType.findUnique({where:{venueObjectId:h.single.id}})).toMatchObject({price:2550,currency:"USD",quantityTotal:1,tariffId:h.tariff});const loaded=await venue.get(owner,raw.id);expect(loaded.layoutJson.version).toBe(2);expect(loaded.layoutJson.version===2&&loaded.layoutJson.editor?.tariffs.find(tariff=>tariff.name==="Inactive draft")?.draftAmount).toBeNull();expect(await prisma.hallTariff.findUnique({where:{id:h.value.paidSeated!.tariffs[1]!.id}})).toMatchObject({active:false,price:null});await expect(tables.update(owner,h.table.id,{price:1})).rejects.toMatchObject({status:409});const updated=await writeUpdate(owner,raw.id,{revision:loaded.revision,layoutJson:loaded.layoutJson});expect((await prisma.venueLayout.findUniqueOrThrow({where:{id:raw.id}})).layoutJson).toEqual(raw.layoutJson);expect(updated.revision).toBe(loaded.revision+1);});
  it("publishes hall inventory for existing whole-table/seat checkout and locks held seats",async()=>{const id=await event(),h=hallDraft();await persist(id,h.value);await prisma.event.update({where:{id},data:{status:"published"}});expect((await booking.options(guest,id)).layout?.version).toBe(2);const publicHall=await new SeatsService(prisma,domain,tables).publicForEvent(id);expect(publicHall?.seats?.some(seat=>seat.id===h.single.id&&seat.availability==="available")).toBe(true);const checkout=await booking.checkoutSeats(guest,randomUUID(),{seatIds:[h.single.id],termsAccepted:true});expect(checkout).toMatchObject({currency:"USD",amountDue:2550});await expect(persist(id,h.value)).rejects.toMatchObject({status:409});await prisma.event.update({where:{id},data:{status:"draft"}});await expect(persist(id,h.value)).rejects.toMatchObject({status:409});await booking.settleFailed(checkout.orderId);await expect(persist(id,h.value)).rejects.toMatchObject({status:409});});
  it("issues finite free registration/QR without a Payment attempt and cancels without refund",async()=>{const id=await event(),value=draft("free");await persist(id,value);await prisma.event.update({where:{id},data:{status:"published"}});const spy=vi.spyOn(provider,"createPaymentLink");const checkout=await booking.checkoutTickets(guest,randomUUID(),{ticketTypeId:value.free.id,quantity:1,termsAccepted:true});expect(checkout.amountDue).toBe(0);expect(checkout.paymentLink).toBe("");expect(spy).not.toHaveBeenCalled();expect(await prisma.payment.count({where:{orderId:checkout.orderId}})).toBe(0);const ticket=await prisma.ticket.findUniqueOrThrow({where:{id:checkout.ticketIds[0]!}});expect(ticket.status).toBe("active");expect(ticket.qrToken.length).toBeGreaterThan(20);await expect(booking.checkoutTickets(guest,randomUUID(),{ticketTypeId:value.free.id,quantity:1,termsAccepted:true})).rejects.toMatchObject({status:409});expect(await booking.cancelTicket(guest,ticket.id,randomUUID())).toMatchObject({cancelled:true,refundPending:false});expect((await prisma.ticketType.findUniqueOrThrow({where:{id:value.free.id}})).quantitySold).toBe(0);const next=await booking.checkoutTickets(guest,randomUUID(),{ticketTypeId:value.free.id,quantity:1,termsAccepted:true});expect(next.amountDue).toBe(0);spy.mockRestore();});
  it("round trips grapheme-limited Unicode tariffs and clones canonical templates without converting currency",async()=>{
    const id=await event(),h=hallDraft(),name="👩‍👩‍👧‍👧".repeat(60);h.value.paidSeated!.tariffs[0]!.content.en!.name=name;h.value.paidSeated!.objects[2]!.annotation="👩‍👩‍👧‍👧".repeat(120);
    await persist(id,h.value);const raw=await prisma.venueLayout.findUniqueOrThrow({where:{eventId:id}}),loaded=await venue.get(owner,raw.id);expect(loaded.layoutJson.version===2&&loaded.layoutJson.editor?.tariffs[0]?.name).toBe(name);
    await writeUpdate(owner,raw.id,{revision:loaded.revision,layoutJson:loaded.layoutJson});const template=await venue.saveTemplate(owner,raw.id,"Canonical fixture");
    expect((await prisma.hallTariff.findFirstOrThrow({where:{venueLayoutId:template.id}})).currency?.trim()).toBe("USD");
    const destination=await event(),applied=await venue.applyTemplate(owner,destination,template.id);expect((await prisma.event.findUniqueOrThrow({where:{id:destination}})).currency?.trim()).toBe("USD");expect((await prisma.table.findFirstOrThrow({where:{venueLayoutId:applied.id}})).price).toBe(2550);expect(applied.canonicalVersion).toBe(3);
    const mismatch=await event();await prisma.event.update({where:{id:mismatch},data:{currency:"KZT"}});await expect(venue.applyTemplate(owner,mismatch,template.id)).rejects.toMatchObject({status:409});await venue.delete(owner,template.id);
  });
  it("rejects overflowing checkout totals before order/reservation creation",async()=>{
    const id=await event(),value=draft("paid_general");value.paidGeneral[0]!.amount=2147483647;await persist(id,value);await prisma.event.update({where:{id},data:{status:"published"}});
    const before=await prisma.order.count({where:{buyerUserId:guest}});await expect(booking.checkoutTickets(guest,randomUUID(),{ticketTypeId:value.paidGeneral[0]!.id,quantity:2,termsAccepted:true})).rejects.toMatchObject({status:400});expect(await prisma.order.count({where:{buyerUserId:guest}})).toBe(before);expect(await prisma.ticketReservation.count({where:{ticketTypeId:value.paidGeneral[0]!.id}})).toBe(0);
  });
  afterAll(async()=>{await prisma.idempotencyRecord.deleteMany({where:{userId:guest}});await prisma.order.deleteMany({where:{buyerUserId:guest}});await prisma.event.deleteMany({where:{id:{in:eventIds}}});await prisma.auditLog.deleteMany({where:{actorId:{in:[owner,guest]}}});await prisma.user.deleteMany({where:{id:{in:[owner,guest]}}});await prisma.$disconnect();});
});

// Current wire payload excludes legacy read-only deposit properties.
function writeUpdate(...args: Parameters<typeof venue.update>) {
 const [owner,id,input]=args; const wire=JSON.parse(JSON.stringify(input, (key,value)=>key==="deposit"?undefined:value)); return venue.update(owner,id,wire);
}
