import { draftDatabaseTests } from "./draft-test-database.js";
import { randomUUID } from "node:crypto";
import { prisma } from "@event-platform/database";
import { loadTranslationEnv } from "@event-platform/config";
import { EVENT_LOCALES,newHallObject,type EventLocale } from "@event-platform/shared-types";
import { afterAll,describe,expect,it,vi } from "vitest";
import { CreationDraftsService } from "./creation-drafts.service.js";
import { DraftTranslationsService } from "./draft-translations.service.js";
import { GoogleV2Translation,decodeTranslationEntities } from "../events/google-v2-translation.js";
import { sha256,type DraftAccess } from "./draft-security.js";
const config={webOrigin:"http://localhost:3000",hmacSecret:"test-only-draft-translation-secret",secureCookies:true,anonymousSeconds:2592000,ownedSeconds:7776000,cleanupGraceSeconds:604800,creationHourlyLimit:100};
const drafts=new CreationDraftsService(prisma,config,[{code:"USD",exponent:2}]),ids:string[]=[],cacheKeys:string[]=[];
function translator(request:typeof fetch,overrides:NodeJS.ProcessEnv={}){return new DraftTranslationsService(drafts,new GoogleV2Translation(loadTranslationEnv({GOOGLE_TRANSLATE_API_KEY:"test-only-key",TRANSLATION_RETRIES:"0",...overrides}),request));}
const response=(texts:string[])=>new Response(JSON.stringify({data:{translations:texts.map(translatedText=>({translatedText}))}}),{headers:{"content-type":"application/json"}});
async function fixture(locale:EventLocale="ru",title=`Title ${randomUUID()}`){const created=await drafts.create(locale,`translations:${randomUUID()}`);ids.push(created.draft.id);const access:DraftAccess={capability:created.capability,csrf:created.draft.csrfToken};const draft=await drafts.update(created.draft.id,access,1,{content:{[locale]:{title}}});return {draft,access};}
function rememberCache(source:EventLocale,target:EventLocale,texts:string[]){for(const text of texts)cacheKeys.push(sha256(`google-v2:text:${source}:${target}:${sha256(text)}`));}
describe.runIf(draftDatabaseTests)("draft locale revisions and Google v2",()=>{
  for(const source of EVENT_LOCALES)for(const target of EVENT_LOCALES)if(source!==target)it(`translates ${source} → ${target} without changing shared values`,async()=>{
    const f=await fixture(source),request=vi.fn<typeof fetch>(async(url,init)=>{expect(String(url)).not.toContain("test-only-key");expect(new Headers(init?.headers).get("X-Goog-Api-Key")).toBe("test-only-key");const body=JSON.parse(init!.body as string);expect(body).toMatchObject({source,target,format:"text"});rememberCache(source,target,body.q);return response(body.q.map((text:string)=>`${target}: ${text}`));});
    const saved=await drafts.update(f.draft.id,f.access,f.draft.revision,{classification:{city:"Shared city"},currency:"USD",acknowledgeCurrencyRelabel:true});
    const result=await translator(request).translate(saved.id,f.access,saved.revision,target);expect(result.draft.aggregate.content[target]?.title).toBe(`${target}: ${saved.aggregate.content[source]!.title}`);expect(result.draft.aggregate.classification).toEqual(saved.aggregate.classification);expect(result.draft.aggregate.currency).toBe("USD");expect(result.draft.aggregate.sourceLocale).toBe(source);expect(result.draft.aggregate.metadata[target]?.title).toMatchObject({origin:"machine",reviewed:false,stale:false,revision:1});
  });
  it("collects both steps, stable ticket/tariff descriptions, refund text and captions",async()=>{
    const f=await fixture("en"),ticket=randomUUID(),tariff=randomUUID(),asset=await prisma.mediaAsset.create({data:{draftId:f.draft.id,kind:"image"}});
    const seat=newHallObject(randomUUID(),"seat",4,4);const {name:_name,description:_description,price:_price,deposit:_deposit,...geometry}=seat;
    const saved=await drafts.update(f.draft.id,f.access,f.draft.revision,{free:{content:{en:{name:"Registration"}}},paidGeneral:[{id:ticket,active:true,amount:1050,capacity:2,content:{en:{name:"Adult",description:"Ticket info"}}}],paidSeated:{version:3,room:{widthM:24,heightM:16},objects:[{...geometry,tariffId:tariff}],tariffs:[{id:tariff,active:true,amount:2500,content:{en:{name:"VIP",description:"Tariff info"}}}]},media:{slots:[asset.id,null,null,null,null],captions:{[asset.id]:{en:"Photo"}}},content:{en:{refundConditions:"Refund info",address:"Address summary"}}});
    const request=vi.fn<typeof fetch>(async(_,init)=>{const body=JSON.parse(init!.body as string);rememberCache("en","kk",body.q);return response(body.q.map((text:string)=>`kk ${text}`));});
    const result=await translator(request).translate(saved.id,f.access,saved.revision,"kk");expect(result.translated).toBe(9);expect(result.draft.aggregate.paidGeneral[0]!.content.kk).toEqual({name:"kk Adult",description:"kk Ticket info"});expect(result.draft.aggregate.paidSeated!.tariffs[0]!.content.kk?.description).toBe("kk Tariff info");expect(result.draft.aggregate.media.captions[asset.id]!.kk).toBe("kk Photo");expect(result.draft.aggregate.free.content.kk?.name).toBe("kk Registration");
  });
  it("replaces existing manual target text directly",async()=>{const f=await fixture("en"),saved=await drafts.update(f.draft.id,f.access,f.draft.revision,{content:{kk:{title:"Manual"}}}),request=vi.fn<typeof fetch>(async()=>{rememberCache("en","kk",[saved.aggregate.content.en!.title!]);return response(["Machine"]);});const result=await translator(request).translate(saved.id,f.access,saved.revision,"kk");expect(result.draft.aggregate.content.kk?.title).toBe("Machine");expect(result.translated).toBe(1);expect(request).toHaveBeenCalledTimes(1);});
  it("rejects late provider responses after target edit, including changed-back text",async()=>{const f=await fixture(),saved=await drafts.update(f.draft.id,f.access,f.draft.revision,{content:{en:{title:"Original"}}});let resolve!:(value:Response)=>void;let started!:(value?:unknown)=>void;const ready=new Promise(r=>started=r),pending=new Promise<Response>(r=>resolve=r),service=translator(async()=>{started();return pending;});rememberCache("ru","en",[saved.aggregate.content.ru!.title!]);const result=service.translate(saved.id,f.access,saved.revision,"en");await ready;const edited=await drafts.update(saved.id,f.access,saved.revision,{content:{en:{title:"New manual"}}});await drafts.update(saved.id,f.access,edited.revision,{content:{en:{title:"Original"}}});resolve(response(["Too late"]));await expect(result).rejects.toMatchObject({status:409});expect((await drafts.read(saved.id,f.access)).aggregate.content.en?.title).toBe("Original");});
  it("retains source-change metadata without a review workflow",async()=>{const f=await fixture("en"),saved=await drafts.update(f.draft.id,f.access,f.draft.revision,{content:{en:{address:"Address summary"},kk:{title:"Manual title",address:"Manual address"}}});const updated=await drafts.update(saved.id,f.access,saved.revision,{content:{en:{title:"Changed source"}},classification:{city:"City"}});expect(updated.aggregate.metadata.kk?.title).toMatchObject({stale:true,origin:"manual"});expect(updated.aggregate.metadata.kk?.address?.stale).toBe(false);});
  it("rejects overlength output without truncation or changing target text",async()=>{const f=await fixture("en"),saved=await drafts.update(f.draft.id,f.access,f.draft.revision,{content:{ru:{title:"Existing"}}});rememberCache("en","ru",[saved.aggregate.content.en!.title!]);const service=translator(async()=>response(["👩‍👩‍👧‍👧".repeat(101)]));await expect(service.translate(saved.id,f.access,saved.revision,"ru")).rejects.toMatchObject({status:400,response:{code:"TRANSLATION_TOO_LONG"}});expect((await drafts.read(saved.id,f.access)).aggregate.content.ru?.title).toBe("Existing");});
  it("caches by exact source hash, bounds quotas across drafts, and authorizes before provider calls",async()=>{const title=`Cache ${randomUUID()}`,a=await fixture("en",title),b=await fixture("en",title);rememberCache("en","kk",[title]);const request=vi.fn<typeof fetch>(async()=>response(["Cached"])),service=translator(request);await expect(service.translate(a.draft.id,{capability:"wrong"},a.draft.revision,"kk")).rejects.toMatchObject({status:404});await service.translate(a.draft.id,a.access,a.draft.revision,"kk");expect((await service.translate(b.draft.id,b.access,b.draft.revision,"kk")).cached).toBe(1);expect(request).toHaveBeenCalledTimes(1);const c=await fixture("en");await expect(translator(request,{TRANSLATION_DAILY_CHARACTERS:"1"}).translate(c.draft.id,c.access,c.draft.revision,"kk")).rejects.toMatchObject({status:429});});
  it("honestly rejects missing credentials while partial manual translation remains available",async()=>{const f=await fixture("en"),service=translator(fetch,{GOOGLE_TRANSLATE_API_KEY:""});await expect(service.translate(f.draft.id,f.access,f.draft.revision,"kk")).rejects.toMatchObject({status:503,response:{code:"TRANSLATION_NOT_CONFIGURED"}});const saved=await drafts.update(f.draft.id,f.access,f.draft.revision,{content:{kk:{address:"Қолмен"}}});expect(saved.aggregate.content.kk?.title).toBeUndefined();expect(saved.aggregate.content.kk?.address).toBe("Қолмен");});
  it("rejects a source edit made during provider latency",async()=>{
    const f=await fixture("en");rememberCache("en","kk",[f.draft.aggregate.content.en!.title!]);let started!:()=>void,finish!:(response:Response)=>void;const ready=new Promise<void>(resolve=>started=resolve),pending=new Promise<Response>(resolve=>finish=resolve),service=translator(async()=>{started();return pending;});
    const result=service.translate(f.draft.id,f.access,f.draft.revision,"kk");await ready;await drafts.update(f.draft.id,f.access,f.draft.revision,{content:{en:{title:"New source"}}});finish(response(["Old translation"]));await expect(result).rejects.toMatchObject({status:409});expect((await drafts.read(f.draft.id,f.access)).aggregate.content.kk?.title).toBeUndefined();
  });
  it("shares the signed-browser request quota across its separate drafts",async()=>{
    const a=await fixture("en"),b=await fixture("en"),quotaScope=`same-browser:${randomUUID()}`;rememberCache("en","kk",[a.draft.aggregate.content.en!.title!]);const request=vi.fn<typeof fetch>(async()=>response(["Translated"])),service=translator(request,{TRANSLATION_HOURLY_REQUESTS:"1"});
    await service.translate(a.draft.id,{...a.access,quotaScope},a.draft.revision,"kk");await expect(service.translate(b.draft.id,{...b.access,quotaScope},b.draft.revision,"kk")).rejects.toMatchObject({status:429});expect(request).toHaveBeenCalledTimes(1);
  });
  afterAll(async()=>{await prisma.mediaAsset.deleteMany({where:{draftId:{in:ids}}});await prisma.eventCreationDraft.deleteMany({where:{id:{in:ids}}});await prisma.draftTranslationCache.deleteMany({where:{key:{in:cacheKeys}}});await prisma.$disconnect();});
});
describe("bounded provider transport",()=>{
  it("retries temporary errors and chunks the documented 128-string limit",async()=>{const request=vi.fn<typeof fetch>().mockResolvedValueOnce(new Response("",{status:503})).mockImplementation(async(_,init)=>{const body=JSON.parse(init!.body as string);expect(body.q.length).toBeLessThanOrEqual(128);return response(body.q);});const result=await new GoogleV2Translation(loadTranslationEnv({GOOGLE_TRANSLATE_API_KEY:"key",TRANSLATION_RETRIES:"1"}),request).translate(Array.from({length:129},(_,i)=>String(i)),"en","ru");expect(result).toHaveLength(129);expect(request).toHaveBeenCalledTimes(3);});
  it("sanitizes failures and rejects incomplete/oversized provider responses",async()=>{const p=(request:typeof fetch)=>new GoogleV2Translation(loadTranslationEnv({GOOGLE_TRANSLATE_API_KEY:"secret",TRANSLATION_RETRIES:"0"}),request);await expect(p(async()=>{throw new Error("secret network URL");}).translate(["Hello"],"en","ru")).rejects.toMatchObject({response:{code:"TRANSLATION_PROVIDER_UNAVAILABLE"}});await expect(p(async()=>response([])).translate(["Hello"],"en","ru")).rejects.toMatchObject({response:{code:"TRANSLATION_INVALID_RESPONSE"}});await expect(p(async()=>new Response("x".repeat(1048577))).translate(["Hello"],"en","ru")).rejects.toMatchObject({response:{code:"TRANSLATION_INVALID_RESPONSE"}});});
  it("enforces the configured request timeout and sanitizes authentication failure",async()=>{
    const config=loadTranslationEnv({GOOGLE_TRANSLATE_API_KEY:"private",TRANSLATION_TIMEOUT_MS:"1000",TRANSLATION_RETRIES:"0"}),pending:typeof fetch=async(_,init)=>new Promise((_,reject)=>init!.signal!.addEventListener("abort",()=>reject(init!.signal!.reason),{once:true}));
    await expect(new GoogleV2Translation(config,pending).translate(["Hello"],"en","ru")).rejects.toMatchObject({response:{code:"TRANSLATION_TIMEOUT"}});
    const denied=vi.fn<typeof fetch>(async()=>new Response("secret provider message",{status:401}));await expect(new GoogleV2Translation({...config,TRANSLATION_RETRIES:2},denied).translate(["Hello"],"en","ru")).rejects.toMatchObject({response:{code:"TRANSLATION_PROVIDER_UNAVAILABLE"}});expect(denied).toHaveBeenCalledTimes(1);
  });
  it("decodes plain text entities without invalid Unicode code points",()=>{expect(decodeTranslationEntities("&amp; &#39; &#x1f600; &#99999999;")).toBe("& ' 😀 &#99999999;");});
});
