import { draftDatabaseTests } from "./draft-test-database.js";
import { randomUUID } from "node:crypto";
import { mkdtemp,readFile,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Readable } from "node:stream";
import { execFileSync } from "node:child_process";
import sharp from "sharp";
import { prisma } from "@event-platform/database";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { CreationDraftsService } from "./creation-drafts.service.js";
import { DraftMediaStorage } from "./draft-media-storage.js";
import { DraftMediaProcessor } from "./draft-media-processor.js";
import { DraftMediaService } from "./draft-media.service.js";

const drafts=new CreationDraftsService(prisma,{webOrigin:"http://localhost:3000",hmacSecret:"media-test-only",secureCookies:true,anonymousSeconds:2592000,ownedSeconds:7776000,cleanupGraceSeconds:604800,creationHourlyLimit:100},[{code:"USD",exponent:2},{code:"KZT",exponent:2}]);
let storage:DraftMediaStorage,processor:DraftMediaProcessor,service:DraftMediaService,directory:string,png:Buffer;
const ids:string[]=[],archiveIDs:string[]=[];
async function fixture(){const created=await drafts.create("en",randomUUID());ids.push(created.draft.id);return {draft:created.draft,access:{capability:created.capability,csrf:created.draft.csrfToken}};}
async function add(f:Awaited<ReturnType<typeof fixture>>,slot:number,data=png,mime:"image/png"|"image/jpeg"|"image/webp"|"video/mp4"|"video/webm"="image/png"){
  const response=await service.reserve(f.draft.id,f.access,{revision:f.draft.revision,slot,bytes:data.length,contentType:mime});f.draft=response.draft;
  const result=await service.upload(f.draft.id,response.asset.id,f.access,Readable.from(data),mime,String(data.length));f.draft=result.draft;return result.asset;
}
describe.runIf(draftDatabaseTests)("private streamed draft media",()=>{
  beforeAll(async()=>{directory=await mkdtemp(join(tmpdir(),"ticket-media-test-"));storage=new DraftMediaStorage({directory,ffmpeg:process.env.MEDIA_FFMPEG_PATH??"ffmpeg",ffprobe:process.env.MEDIA_FFPROBE_PATH??"ffprobe",imageBytes:10*1024**2,videoBytes:100*1024**2,videoSeconds:60,draftBytes:250*1024**2});processor=new DraftMediaProcessor(storage);service=new DraftMediaService(drafts,storage,processor);png=await sharp({create:{width:160,height:100,channels:3,background:"violet"}}).png().toBuffer();});
  it("keeps exact positions and 3/1/0 empty slots at 2/4/5 uploads",async()=>{const f=await fixture();const first=await add(f,2);await add(f,4);let restored=await drafts.read(f.draft.id,f.access);expect(restored.aggregate.media.slots[2]).toBe(first.id);expect(restored.aggregate.media.slots.filter(id=>!id)).toHaveLength(3);await add(f,0);await add(f,3);expect(f.draft.aggregate.media.slots.filter(id=>!id)).toHaveLength(1);await add(f,1);expect(f.draft.aggregate.media.slots.filter(id=>!id)).toHaveLength(0);restored=await drafts.read(f.draft.id,f.access);expect(restored.aggregate.media.cardAssetId).toBe(first.id);expect(restored.aggregate.media.backgroundAssetId).toBe(first.id);await expect(service.reserve(f.draft.id,f.access,{revision:f.draft.revision,slot:5,bytes:png.length,contentType:"image/png"})).rejects.toMatchObject({status:422});});
  it("serializes simultaneous fifth/sixth reservations",async()=>{const f=await fixture();for(let slot=0;slot<4;slot++)await add(f,slot);const request={revision:f.draft.revision,slot:4,bytes:png.length,contentType:"image/png" as const};const results=await Promise.allSettled([service.reserve(f.draft.id,f.access,request),service.reserve(f.draft.id,f.access,request)]);expect(results.filter(result=>result.status==="fulfilled")).toHaveLength(1);expect(await prisma.mediaAsset.count({where:{draftId:f.draft.id}})).toBe(5);});
  it("preserves roles and originals through reorder/crops; deletion clears only its slot",async()=>{const f=await fixture(),a=await add(f,1),b=await add(f,4);f.draft=await drafts.update(f.draft.id,f.access,f.draft.revision,{media:{slots:[b.id,null,a.id,null,null],crops:{card:{focalX:0.2,focalY:0.8,zoom:2}}}});expect(f.draft.aggregate.media.cardAssetId).toBe(a.id);expect(await readFile(storage.path(a.id))).toEqual(png);f.draft=await service.remove(f.draft.id,a.id,f.access,f.draft.revision);expect(f.draft.aggregate.media.slots[2]).toBeNull();expect(f.draft.aggregate.media.cardAssetId).toBe(b.id);expect(f.draft.aggregate.media.backgroundAssetId).toBe(b.id);expect(await service.collect(b.id)).toBe(false);expect(await readFile(storage.path(b.id))).toEqual(png);});
  it("validates JPEG/PNG/WebP decoded dimensions, strips metadata and rejects disguised files",async()=>{const f=await fixture();for(const format of ["jpeg","png","webp"] as const){const data=await sharp(png).withMetadata({orientation:6}).toFormat(format).toBuffer();const asset=await add(f,format==="jpeg"?0:format==="png"?1:2,data,`image/${format}`);expect(asset.state).toBe("ready");expect(asset.width).toBe(100);expect(asset.height).toBe(160);expect((await sharp(storage.path(asset.id,"display.webp")).metadata()).exif).toBeUndefined();}const reserved=await service.reserve(f.draft.id,f.access,{revision:f.draft.revision,slot:3,bytes:png.length,contentType:"image/jpeg"});await expect(service.upload(f.draft.id,reserved.asset.id,f.access,Readable.from(png),"image/jpeg")).rejects.toMatchObject({status:400});expect((await prisma.mediaAsset.findUniqueOrThrow({where:{id:reserved.asset.id}})).state).toBe("failed");});
  it("rejects oversized reservations, cross-draft reads and publication of unfinished files",async()=>{const f=await fixture(),b=await fixture();await expect(service.reserve(f.draft.id,f.access,{revision:1,slot:0,bytes:10*1024**2+1,contentType:"image/png"})).rejects.toMatchObject({status:422});await expect(service.list(f.draft.id,b.access)).rejects.toMatchObject({status:404});const reserved=await service.reserve(f.draft.id,f.access,{revision:1,slot:0,bytes:png.length,contentType:"image/png"});const result=await drafts.validate(f.draft.id,f.access,reserved.draft.revision);expect(result.fields.some(field=>field.code==="MEDIA_NOT_READY")).toBe(true);});
  it("never collects published or historically referenced media",async()=>{const f=await fixture(),asset=await add(f,0);await prisma.mediaAsset.update({where:{id:asset.id},data:{publishedAt:new Date()}});f.draft=await drafts.update(f.draft.id,f.access,f.draft.revision,{media:{slots:[null,null,null,null,null],cardAssetId:null,backgroundAssetId:null}});expect(await service.collect(asset.id)).toBe(false);const other=await add(f,2);const archive=randomUUID();archiveIDs.push(archive);await prisma.legacyEventSnapshot.create({data:{eventId:archive,fingerprint:"a".repeat(64),original:{media:other.id}}});await drafts.update(f.draft.id,f.access,f.draft.revision,{media:{slots:[null,null,null,null,null],cardAssetId:null,backgroundAssetId:null}});expect(await service.collect(other.id)).toBe(false);});
  it("decodes MP4/WebM, generates posters and forbids video as Main",async()=>{for(const format of ["mp4","webm"] as const){const f=await fixture(),path=join(directory,`fixture.${format}`);execFileSync(storage.config.ffmpeg,["-nostdin","-v","error","-f","lavfi","-i","color=c=blue:s=160x100:d=1","-c:v",format==="mp4"?"libx264":"libvpx","-y",path]);const asset=await add(f,4,await readFile(path),`video/${format}`);expect(asset.durationSeconds).toBeGreaterThan(0);expect(asset.state).toBe("ready");expect((await sharp(storage.path(asset.id,"poster.webp")).metadata()).width).toBeGreaterThan(0);expect(f.draft.aggregate.media.cardAssetId).toBeNull();await expect(drafts.update(f.draft.id,f.access,f.draft.revision,{media:{cardAssetId:asset.id}})).rejects.toMatchObject({status:422});}},30000);
  it("rejects decoded video duration limits and reports absent processors honestly",async()=>{const f=await fixture(),path=join(directory,"long.mp4");execFileSync(storage.config.ffmpeg,["-nostdin","-v","error","-f","lavfi","-i","color=s=64x64:d=2","-c:v","libx264","-y",path]);const bytes=await readFile(path),reserved=await service.reserve(f.draft.id,f.access,{revision:1,slot:0,bytes:bytes.length,contentType:"video/mp4"});const original=storage.config.videoSeconds;storage.config.videoSeconds=1;await expect(service.upload(f.draft.id,reserved.asset.id,f.access,Readable.from(bytes),"video/mp4")).rejects.toMatchObject({status:422});storage.config.videoSeconds=original;const ffprobe=storage.config.ffprobe;storage.config.ffprobe="/missing/ffprobe";await expect(processor.process(reserved.asset.id,"video/mp4")).rejects.toMatchObject({status:503});storage.config.ffprobe=ffprobe;},30000);
  afterAll(async()=>{await prisma.legacyEventSnapshot.deleteMany({where:{eventId:{in:archiveIDs}}});await prisma.mediaAsset.deleteMany({where:{draftId:{in:ids}}});await prisma.eventCreationDraft.deleteMany({where:{id:{in:ids}}});await rm(directory,{recursive:true,force:true});await prisma.$disconnect();});
});
