import { draftDatabaseTests } from "./draft-test-database.js";
import { randomUUID } from "node:crypto";
import { prisma } from "@event-platform/database";
import { DEFAULT_MEDIA_CROP,newEventCreationDraft,newHallObject,editorHallV3,type EventCreationDraftV2 } from "@event-platform/shared-types";
import { beforeAll,afterAll,describe,expect,it,vi } from "vitest";
import { CreationDraftsService } from "./creation-drafts.service.js";
import { DraftPublicationService } from "./draft-publication.service.js";
import { csrfFor,type DraftAccess,type DraftConfig } from "./draft-security.js";
import { DomainEventsService } from "../domain-events/domain-events.service.js";
import { TablesService } from "../tables/tables.service.js";
import { TicketTypesService } from "../ticket-types/ticket-types.service.js";
import { MyEventsService } from "../my-events/my-events.service.js";
import { BookingService } from "../booking/booking.service.js";
import { DevelopmentPaymentProvider } from "../booking/payment-provider.js";
import { PaymentService } from "../payments/payment.service.js";
import { CheckoutEmailService } from "../booking/checkout-email.service.js";
import { RefundService } from "../booking/refund.service.js";
import { TicketsService } from "../tickets/tickets.service.js";
import { readCheckoutSnapshot } from "@event-platform/shared-types";
import { PublicEventsService } from "../public-events/public-events.service.js";
const config:DraftConfig={webOrigin:"http://localhost:3000",hmacSecret:"test-publication-secret",secureCookies:true,anonymousSeconds:86400,ownedSeconds:86400,cleanupGraceSeconds:86400,creationHourlyLimit:200};
const service=new CreationDraftsService(prisma,config,[{code:"KZT",exponent:2},{code:"USD",exponent:2}]),publication=new DraftPublicationService(service,{organizerRequiresApproval:false} as never),blocked=new DraftPublicationService(service,{organizerRequiresApproval:true} as never),domain=new DomainEventsService(),tables=new TablesService(prisma,domain,{holdTtlSeconds:600,cleanupIntervalSeconds:60},{now:()=>new Date()}),types=new TicketTypesService(prisma,domain),publicEvents=new PublicEventsService(prisma,types,tables);
const clock={now:()=>new Date()},provider=new DevelopmentPaymentProvider("http://localhost:3000","publication-webhook-secret"),payments=new PaymentService(prisma,provider,domain,clock),booking=new BookingService(prisma,types,tables,domain,{checkoutTtlSeconds:900,cleanupIntervalSeconds:60},clock,payments,new CheckoutEmailService({} as never)),refunds=new RefundService(prisma,provider,domain,clock),wallet={isConfigured:()=>true,generate:vi.fn(async()=>Buffer.from("test pass"))},tickets=new TicketsService(prisma,domain,wallet as never);
const guest=randomUUID(),other=randomUUID(),organizer=randomUUID(),ids:string[]=[],events:string[]=[];
async function fixture(mode:EventCreationDraftV2["selectedMode"]="paid_general"){
 const result=await service.create("en",randomUUID());ids.push(result.draft.id);const id=result.draft.id,assetId=randomUUID(),access:DraftAccess={capability:result.capability,quotaScope:`browser:${randomUUID()}`};access.csrf=csrfFor(id,access,config.hmacSecret,true);
 await prisma.mediaAsset.create({data:{id:assetId,draftId:id,kind:"image",state:"ready",storageKey:`${assetId}/original`,checksum:"a".repeat(64),contentType:"image/png",bytes:100n,width:800,height:500,derivatives:{display:"display.webp",thumbnail:"thumbnail.webp"}}});
 const draft=newEventCreationDraft(randomUUID(),"en");draft.selectedMode=mode;draft.currency="USD";draft.content.en={title:`Publish ${id}`,description:"A real description",address:"Address",refundConditions:"Contact us before the event"};draft.classification={countryCode:"KZ",city:"Almaty",category:"music",ageRestriction:0};draft.schedule={startLocal:"2030-12-01T20:00",endLocal:"2030-12-02T01:00",timezone:"Asia/Almaty",startChoice:null,endChoice:null};draft.refundsAvailable=true;draft.free.capacity=1;draft.free.content.en={name:"Registration"};draft.paidGeneral=[{id:randomUUID(),active:true,amount:1234,capacity:1,content:{en:{name:"Adult"}}}];draft.media.slots[1]=assetId;draft.media.cardAssetId=assetId;draft.media.backgroundAssetId=assetId;
 if(mode==="paid_seated"){const tariff=randomUUID(),tableId=randomUUID();draft.paidSeated=editorHallV3({widthM:20,heightM:20},{version:1,objects:[{...newHallObject(randomUUID(),"seat",4,4),number:1,tariffId:tariff},{...newHallObject(tableId,"table_rect",10,10),number:1,tariffId:tariff,saleMode:"whole_table" as const},{...newHallObject(randomUUID(),"seat",10,9),parentId:tableId,side:"top" as const}],tariffs:[{id:tariff,name:"VIP",color:"#6320ee",price:2300}]},null,"en");}
 draft.media.assetCrops[assetId]={...DEFAULT_MEDIA_CROP};
 const saved=await service.mutate(id,access,1,()=>draft);return {id,assetId,access,draft,saved};
}
function authenticated(id:string,access:DraftAccess,userId=guest,owned=false){const result={...access,principal:{userId,role:"guest" as const,sessionFamilyId:"fixture-family"}};result.csrf=csrfFor(id,result,config.hmacSecret,!owned);return result;}
async function publishFixture(mode:EventCreationDraftV2["selectedMode"]="paid_general"){const f=await fixture(mode),intent=await publication.intent(f.id,f.access,f.saved.revision),access=authenticated(f.id,f.access),result=await publication.publish(f.id,intent.id,access);events.push(result.eventId);return {...f,intent,result,owner:authenticated(f.id,f.access,guest,true)};}
async function settle(orderId:string){const payment=await prisma.payment.findFirstOrThrow({where:{orderId}});const signed=DevelopmentPaymentProvider.signWebhook({eventId:randomUUID(),eventType:"payment.succeeded",providerPaymentId:payment.providerPaymentId!,orderId,amount:payment.amount,currency:payment.currency},"publication-webhook-secret",Math.floor(Date.now()/1000));await booking.handlePaymentWebhook(provider.verifyWebhook({rawBody:signed.rawBody,headers:signed.headers,now:new Date()}));}
describe.runIf(draftDatabaseTests)("atomic creation publication and owned editing",()=>{
 beforeAll(async()=>{await prisma.user.createMany({data:[{id:guest,role:"guest"},{id:other,role:"guest"},{id:organizer,role:"organizer"}]});});
 for(const mode of ["free","paid_general","paid_seated"] as const)it(`publishes ${mode} with normalized inventory, schedule, roles and one outbox`,async()=>{const f=await publishFixture(mode),event=await prisma.event.findUniqueOrThrow({where:{id:f.result.eventId},include:{contents:true,mediaLinks:true,ticketTypes:true}});expect(event).toMatchObject({status:"published",creationVersion:2,v2State:"reconciled",saleMode:mode,currency:"USD",refundsAvailable:mode!=="free"});expect(event.endsAt!.getTime()).toBeGreaterThan(event.startsAt!.getTime());expect(event.mediaLinks[0]).toMatchObject({slot:1,isCard:true,isBackground:true});expect(event.contents[0]).toMatchObject({locale:"en",});expect(await prisma.outboxEvent.count({where:{aggregateId:event.id,eventType:"event.published"}})).toBe(1);expect(f.result.user.role).toBe("organizer");expect(await service.read(f.id,f.owner)).toMatchObject({state:"published",resultEventId:event.id});await expect(service.read(f.id,f.access)).rejects.toMatchObject({status:404});});
 it("returns one event for simultaneous publication, callback replay and a lost response",async()=>{const f=await fixture(),intent=await publication.intent(f.id,f.access,f.saved.revision),access=authenticated(f.id,f.access,organizer);const results=await Promise.allSettled([publication.publish(f.id,intent.id,access),publication.publish(f.id,intent.id,access)]);const completed=results.find(result=>result.status==="fulfilled");expect(completed?.status).toBe("fulfilled");if(completed?.status!=="fulfilled")throw new Error("No publication");const result=completed.value;events.push(result.eventId);const reloaded=await service.read(f.id,authenticated(f.id,f.access,organizer,true));const replay=await publication.publish(f.id,intent.id,{...authenticated(f.id,f.access,organizer,true),csrf:reloaded.csrfToken});expect(replay.eventId).toBe(result.eventId);expect(await prisma.event.count({where:{creationDraft:{id:f.id}}})).toBe(1);expect(await prisma.outboxEvent.count({where:{aggregateId:result.eventId,eventType:"event.published"}})).toBe(1);});
 it("preserves drafts and identity role on organizer approval failure",async()=>{const f=await fixture(),intent=await blocked.intent(f.id,f.access,f.saved.revision);await expect(blocked.publish(f.id,intent.id,authenticated(f.id,f.access,other))).rejects.toMatchObject({status:409});expect(await service.read(f.id,f.access)).toMatchObject({state:"active",revision:f.saved.revision});expect((await prisma.user.findUniqueOrThrow({where:{id:other}})).role).toBe("guest");expect((await prisma.eventPublishIntent.findUniqueOrThrow({where:{id:intent.id}})).consumedAt).toBeNull();});
 it("rejects changed or expired intent and preserves every saved field",async()=>{const f=await fixture(),intent=await publication.intent(f.id,f.access,f.saved.revision);const updated=await service.update(f.id,f.access,f.saved.revision,{content:{en:{title:"Changed after login cancellation"}}});await expect(publication.publish(f.id,intent.id,authenticated(f.id,f.access))).rejects.toMatchObject({status:409});expect((await service.read(f.id,f.access)).aggregate.content.en?.title).toBe("Changed after login cancellation");const next=await publication.intent(f.id,f.access,updated.revision);await prisma.eventPublishIntent.update({where:{id:next.id},data:{expiresAt:new Date(Date.now()-100),createdAt:new Date(Date.now()-10000)}});await expect(publication.publish(f.id,next.id,authenticated(f.id,f.access))).rejects.toMatchObject({status:409});});
 it("rejects cross-browser/account/draft intents, unauthenticated POST and invalid CSRF",async()=>{const f=await fixture(),g=await fixture(),intent=await publication.intent(f.id,f.access,f.saved.revision);await expect(publication.publish(f.id,intent.id,f.access)).rejects.toMatchObject({status:401});await expect(publication.publish(f.id,intent.id,{...authenticated(f.id,f.access),csrf:"wrong"})).rejects.toMatchObject({status:403});await expect(publication.publish(f.id,intent.id,{...authenticated(f.id,f.access),quotaScope:"browser:foreign"})).rejects.toMatchObject({status:404});await expect(publication.publish(g.id,intent.id,authenticated(g.id,g.access))).rejects.toMatchObject({status:404});const claimed=await service.claim(f.id,authenticated(f.id,f.access,organizer),f.saved.revision);await expect(publication.publish(f.id,intent.id,authenticated(f.id,f.access,other,true))).rejects.toMatchObject({status:404});expect(claimed.owned).toBe(true);});
 it("validates before making an intent and never creates placeholder Events",async()=>{const f=await fixture();const before=await prisma.event.count();await prisma.mediaAsset.update({where:{id:f.assetId},data:{state:"processing"}});await expect(publication.intent(f.id,f.access,f.saved.revision)).rejects.toMatchObject({status:422});expect(await prisma.eventPublishIntent.count({where:{draftId:f.id}})).toBe(0);expect(await prisma.event.count()).toBe(before);});
 it("rolls back claim, inventory, media and intent when the outbox write fails",async()=>{const f=await fixture(),intent=await publication.intent(f.id,f.access,f.saved.revision),spy=vi.spyOn(publication as unknown as {record:()=>Promise<void>},"record").mockRejectedValueOnce(new Error("outbox rejected"));await expect(publication.publish(f.id,intent.id,authenticated(f.id,f.access))).rejects.toThrow("outbox rejected");spy.mockRestore();expect(await service.read(f.id,f.access)).toMatchObject({state:"active",owned:false,resultEventId:null});expect((await prisma.mediaAsset.findUniqueOrThrow({where:{id:f.assetId}})).eventId).toBeNull();expect((await prisma.eventPublishIntent.findUniqueOrThrow({where:{id:intent.id}})).consumedAt).toBeNull();expect(await prisma.ticketType.count({where:{id:f.draft.paidGeneral[0]!.id}})).toBe(0);});
 it("opens the same protected editor, preserves roles, and commits text without changing inventory",async()=>{const f=await publishFixture(),access=authenticated(f.id,f.access,guest,true),editor=await publication.openOwned(f.result.eventId,access),editing={...access,csrf:editor.csrfToken};expect(editor.editingEventId).toBe(f.result.eventId);expect(editor.aggregate.media).toEqual(f.draft.media);const saved=await service.update(editor.id,editing,editor.revision,{content:{en:{title:"New current title"},kk:{title:"Incomplete"}}});await publication.saveOwned(editor.id,editing,saved.revision);expect((await publicEvents.get(f.result.eventId,new Date(),"kk")).title).toBe("New current title");const again=await publication.openOwned(f.result.eventId,access);expect(again.id).toBe(editor.id);const invalid=await service.update(editor.id,editing,saved.revision,{paidGeneral:saved.aggregate.paidGeneral.map(row=>({...row,amount:999}))});await expect(publication.saveOwned(editor.id,editing,invalid.revision)).rejects.toMatchObject({status:409});expect((await prisma.ticketType.findUniqueOrThrow({where:{id:f.draft.paidGeneral[0]!.id}})).price).toBe(1234);await expect(publication.openOwned(f.result.eventId,authenticated(f.id,f.access,other,true))).rejects.toMatchObject({status:404});});
 it("shows a coherent locale and only searches displayed normalized text",async()=>{const f=await publishFixture(),editor=await publication.openOwned(f.result.eventId,f.owner),access={...f.owner,csrf:editor.csrfToken};const target={title:`Target ${randomUUID()}`,description:"Target description",address:"Target address",refundConditions:"Target refund"};let saved=await service.update(editor.id,access,editor.revision,{content:{en:{title:`Source ${randomUUID()}`},kk:target},paidGeneral:editor.aggregate.paidGeneral.map(row=>({...row,content:{...row.content,kk:{name:"Ересек"}}}))});await publication.saveOwned(editor.id,access,saved.revision);const result=await publicEvents.get(f.result.eventId,new Date(),"kk");expect(result).toMatchObject({title:target.title,contentLocale:"kk",saleMode:"paid_general"});expect(result.ticketTypes[0]?.name).toBe("Ересек");expect(result.media?.map(asset=>asset.slot)).toEqual([1]);expect((await publicEvents.list({locale:"kk",page:1,limit:20,sort:"recent",search:target.title})).items.map(item=>item.id)).toContain(f.result.eventId);saved=await service.update(editor.id,access,saved.revision,{content:{en:{title:"Changed source"}}});await publication.saveOwned(editor.id,access,saved.revision);expect((await publicEvents.get(f.result.eventId,new Date(),"kk")).contentLocale).toBe("en");expect((await publicEvents.list({locale:"kk",page:1,limit:20,sort:"recent",search:target.title})).total).toBe(0);});
 it("freezes a non-KZT paid promise across edits, retries, wallet and refunds",async()=>{
 const f=await publishFixture(),input={ticketTypeId:f.draft.paidGeneral[0]!.id,quantity:1,termsAccepted:true as const,contentLocale:"en" as const,policyRevision:1},key=randomUUID();
 await expect(booking.checkoutTickets(other,randomUUID(),{...input,policyRevision:0})).rejects.toMatchObject({status:409});
 const checkout=await booking.checkoutTickets(other,key,input);expect(await booking.checkoutTickets(other,key,input)).toMatchObject({orderId:checkout.orderId});expect(checkout).toMatchObject({amountDue:1234,currency:"USD",paymentMode:"full_payment"});
 const order=await prisma.order.findUniqueOrThrow({where:{id:checkout.orderId}}),frozen=order.checkoutSnapshot;expect(frozen).toMatchObject({version:2,title:f.draft.content.en!.title,currency:"USD",amount:1234,refund:{revision:1,conditions:"Contact us before the event"}});expect(await prisma.payment.count({where:{orderId:order.id}})).toBe(1);await settle(order.id);
 const editor=await publication.openOwned(f.result.eventId,f.owner),access={...f.owner,csrf:editor.csrfToken},saved=await service.update(editor.id,access,editor.revision,{content:{en:{title:"Renamed current event",address:"New address"}},refundsAvailable:false});await publication.saveOwned(editor.id,access,saved.revision);
 expect((await prisma.order.findUniqueOrThrow({where:{id:order.id}})).checkoutSnapshot).toEqual(frozen);expect(readCheckoutSnapshot(frozen)).toMatchObject({address:"Address",cancellationTerms:"Contact us before the event"});expect(await tickets.getForUser(other,checkout.ticketIds[0]!,"kk")).toMatchObject({eventTitle:f.draft.content.en!.title,contentLocale:"en"});expect((await new MyEventsService(prisma).list(other,"upcoming",1,100,new Date(),"kk")).items.find(row=>row.id===f.result.eventId)?.tickets[0]?.ticketTypeName).toBe("Adult");await tickets.walletPassForUser(other,checkout.ticketIds[0]!);expect(wallet.generate).toHaveBeenLastCalledWith(expect.objectContaining({eventTitle:f.draft.content.en!.title,address:"Address"}));
 const refund=await refunds.request(guest,f.result.eventId,order.id,"Cancelled event");expect(refund).toMatchObject({amount:1234,currency:"USD",status:"succeeded"});expect((await prisma.refundRequest.findUniqueOrThrow({where:{id:refund.id}})).acceptedSnapshot).toMatchObject({version:2,amount:1234,currency:"USD",acceptedPolicyRevision:1,exceptional:false});
 await expect(booking.checkoutTickets(other,randomUUID(),input)).rejects.toMatchObject({status:409});
 });
 it("serializes last free registration, issues QR without payment and restores capacity on cancellation",async()=>{
 const f=await publishFixture("free"),input={ticketTypeId:f.draft.free.id,quantity:1,termsAccepted:true as const,contentLocale:"en" as const,policyRevision:1};const results=await Promise.allSettled([booking.checkoutTickets(other,randomUUID(),input),booking.checkoutTickets(other,randomUUID(),input)]),won=results.find(row=>row.status==="fulfilled");expect(results.filter(row=>row.status==="fulfilled")).toHaveLength(1);if(won?.status!=="fulfilled")throw new Error("No registration");const checkout=won.value;expect(checkout.amountDue).toBe(0);expect(await prisma.payment.count({where:{orderId:checkout.orderId}})).toBe(0);const ticket=await prisma.ticket.findUniqueOrThrow({where:{id:checkout.ticketIds[0]!}});expect(ticket).toMatchObject({status:"active"});expect(ticket.qrToken.length).toBeGreaterThan(20);expect(readCheckoutSnapshot((await prisma.order.findUniqueOrThrow({where:{id:checkout.orderId}})).checkoutSnapshot).acceptedPolicy?.freeCancellation).toBe(true);expect(await booking.cancelTicket(other,ticket.id,randomUUID())).toMatchObject({refundPending:false});expect((await booking.checkoutTickets(other,randomUUID(),input)).amountDue).toBe(0);
 });
 it("sells normalized hall seats and whole tables with exact frozen resources",async()=>{
 const f=await publishFixture("paid_seated"),seat=f.draft.paidSeated!.objects.find(row=>row.type==="seat"&&!row.parentId)!,table=f.draft.paidSeated!.objects.find(row=>row.type==="table_rect")!,input={seatIds:[seat.id],termsAccepted:true as const,contentLocale:"en" as const,policyRevision:1};const results=await Promise.allSettled([booking.checkoutSeats(other,randomUUID(),input),booking.checkoutSeats(other,randomUUID(),input)]),won=results.find(row=>row.status==="fulfilled");if(won?.status!=="fulfilled")throw results[0]!.status==="rejected"?results[0]!.reason:new Error("No seat");expect(results.filter(row=>row.status==="fulfilled")).toHaveLength(1);expect(won.value).toMatchObject({amountDue:2300,currency:"USD"});expect((await prisma.order.findUniqueOrThrow({where:{id:won.value.orderId}})).checkoutSnapshot).toMatchObject({version:2,items:[{resourceId:seat.id,kind:"seat",name:"VIP · Seat 1",unitAmount:2300}]});await settle(won.value.orderId);
 const whole=await booking.checkoutTable(other,randomUUID(),{tableId:table.id,termsAccepted:true as const,contentLocale:"en",policyRevision:1});await settle(whole.orderId);expect(await prisma.groupPass.findUnique({where:{orderId:whole.orderId}})).toMatchObject({status:"active"});expect((await prisma.order.findUniqueOrThrow({where:{id:whole.orderId}})).checkoutSnapshot).toMatchObject({version:2,saleMode:"paid_seated",currency:"USD",amount:2300,items:[{kind:"table",resourceId:table.id}]});
 });
 it("honors an accepted No-refund policy and records an exceptional organizer refund",async()=>{
 const f=await publishFixture(),editor=await publication.openOwned(f.result.eventId,f.owner),access={...f.owner,csrf:editor.csrfToken},saved=await service.update(editor.id,access,editor.revision,{refundsAvailable:false});await publication.saveOwned(editor.id,access,saved.revision);
 const input={ticketTypeId:f.draft.paidGeneral[0]!.id,quantity:1,termsAccepted:true as const,policyRevision:2,contentLocale:"en" as const};await expect(booking.checkoutTickets(other,randomUUID(),{...input,contentLocale:"kk"})).rejects.toMatchObject({status:409});const checkout=await booking.checkoutTickets(other,randomUUID(),input);await settle(checkout.orderId);await expect(booking.cancelTicket(other,checkout.ticketIds[0]!,randomUUID())).rejects.toMatchObject({status:409});expect(await booking.ticketCancellationTerms(other,checkout.ticketIds[0]!)).toMatchObject({acceptedPolicy:{available:false,revision:2}});const refund=await refunds.request(guest,f.result.eventId,checkout.orderId,"Organizer approved exception");expect((await prisma.refundRequest.findUniqueOrThrow({where:{id:refund.id}})).acceptedSnapshot).toMatchObject({exceptional:true,acceptedPolicyRevision:2,currency:"USD",amount:1234});
 });
 it("settles one normalized combined hall order with table admissions and exact minor-unit totals",async()=>{
 const f=await publishFixture("paid_seated"),hall=f.draft.paidSeated!,seat=hall.objects.find(row=>row.type==="seat"&&!row.parentId)!,table=hall.objects.find(row=>row.type==="table_rect")!,input={eventId:f.result.eventId,tickets:[],seatIds:[seat.id],tableId:table.id,termsAccepted:true as const,policyRevision:1,contentLocale:"en" as const},key=randomUUID(),checkout=await booking.checkoutCart(other,key,input);expect(await booking.checkoutCart(other,key,input)).toMatchObject({orderId:checkout.orderId});expect(checkout).toMatchObject({amountDue:4600,currency:"USD"});await settle(checkout.orderId);const order=await prisma.order.findUniqueOrThrow({where:{id:checkout.orderId}});expect(order.checkoutSnapshot).toMatchObject({version:2,amount:4600,selection:{kind:"cart",groupPass:true}});expect(readCheckoutSnapshot(order.checkoutSnapshot).items).toHaveLength(2);expect(await prisma.ticket.count({where:{orderId:order.id,status:"active"}})).toBe(2);expect(await prisma.groupPass.findUnique({where:{orderId:order.id}})).toMatchObject({status:"active",totalSeats:1});expect(await prisma.payment.count({where:{orderId:order.id,status:"paid"}})).toBe(1);
 });
 afterAll(async()=>{const orderIds=(await prisma.order.findMany({where:{buyerUserId:other},select:{id:true}})).map(row=>row.id);await prisma.refundRequest.deleteMany({where:{orderId:{in:orderIds}}});await prisma.webhookEvent.deleteMany({where:{orderId:{in:orderIds}}});await prisma.idempotencyRecord.deleteMany({where:{userId:other}});await prisma.order.deleteMany({where:{id:{in:orderIds}}});await prisma.outboxEvent.deleteMany({where:{aggregateId:{in:orderIds}}});await prisma.event.updateMany({where:{id:{in:events}},data:{status:"draft"}});await prisma.eventPublishIntent.deleteMany({where:{draftId:{in:ids}}});await prisma.eventCreationDraft.deleteMany({where:{editingEventId:{in:events}}});await prisma.eventCreationDraft.updateMany({where:{id:{in:ids}},data:{state:"deleted",resultEventId:null}});await prisma.eventMedia.deleteMany({where:{eventId:{in:events}}});await prisma.mediaAsset.deleteMany({where:{draftId:{in:ids}}});await prisma.eventCreationDraft.deleteMany({where:{id:{in:ids}}});await prisma.event.deleteMany({where:{id:{in:events}}});await prisma.auditLog.deleteMany({where:{actorId:{in:[guest,other,organizer]}}});await prisma.outboxEvent.deleteMany({where:{aggregateId:{in:events}}});await prisma.user.deleteMany({where:{id:{in:[guest,other,organizer]}}});await prisma.$disconnect();});
});
