"use client";
import type { EventLocale } from "@event-platform/shared-types";
import { EventDescription } from "./event-description";
const words={ru:{about:"О событии",location:"Место",refund:"Возврат и отмена",none:"Возврат денежных средств не предусмотрен.",free:"Бесплатную регистрацию можно отменить без денежного возврата."},en:{about:"About the event",location:"Venue",refund:"Refunds and cancellation",none:"Monetary refunds are not available.",free:"Free registrations can be cancelled without a monetary refund."},kk:{about:"Іс-шара туралы",location:"Өтетін орын",refund:"Қайтарым және бас тарту",none:"Ақшалай қайтарым қарастырылмаған.",free:"Тегін тіркелуді ақшалай қайтарымсыз тоқтатуға болады."}};
export function EventStory({description,address,refundConditions,refundsAvailable,free,locale,showRefund=true}:{description:string|null;address:string;refundConditions:string|null;refundsAvailable:boolean;free:boolean;locale:EventLocale;showRefund?:boolean}){const c=words[locale];return <div className="space-y-8">{description?<section><h2 className="mb-3 text-xl font-semibold">{c.about}</h2><EventDescription value={description} /></section>:null}{address?<section><h2 className="mb-3 text-xl font-semibold">{c.location}</h2><p className="text-slate-600 dark:text-ticket-muted">{address}</p></section>:null}{showRefund?<section><h2 className="mb-3 text-xl font-semibold">{c.refund}</h2><p className="whitespace-pre-wrap break-words text-slate-700 dark:text-ticket-muted">{free?c.free:refundsAvailable?refundConditions:c.none}</p></section>:null}</div>;}

export function RefundPolicyText({locale,free,available,conditions}:{locale:EventLocale;free:boolean;available:boolean;conditions:string|null}){const c=words[locale];return <p className="whitespace-pre-wrap text-sm">{free?c.free:available?conditions:c.none}</p>;}

export function EventRefund({locale,free,available,conditions}:{locale:EventLocale;free:boolean;available:boolean;conditions:string|null}) { return <section><h2 className="mb-3 text-xl font-semibold">{words[locale].refund}</h2><RefundPolicyText locale={locale} free={free} available={available} conditions={conditions}/></section>; }
