"use client";
import { useEffect,useRef,useState } from "react";
import { selectContentLocale,assetMediaCrop,type MediaCrop,type DraftMediaResponse,type EventLocale } from "@event-platform/shared-types";
import type { DraftAutosave } from "../../lib/creation-draft-client";
import { creationDraftRequest } from "../../lib/creation-draft-client";
import { FramedMedia } from "./framed-media";
import { usePrivateMedia } from "./media-grid";
import { EventStory } from "../event-presentation";
const copy={ru:{title:"Предпросмотр",close:"Закрыть",fallback:"Показан исходный язык",tickets:"Билеты"},en:{title:"Preview",close:"Close",fallback:"Showing the source language",tickets:"Tickets"},kk:{title:"Алдын ала қарау",close:"Жабу",fallback:"Бастапқы тіл көрсетілген",tickets:"Билеттер"}};
export function DraftPreview({client,locale,contentLocale,onClose}:{client:DraftAutosave;locale:EventLocale;contentLocale:EventLocale;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[assets,setAssets]=useState<DraftMediaResponse[]>([]),draft=client.aggregate,c=copy[locale],selection=selectContentLocale(draft,contentLocale),content=draft.content[selection.locale];
 useEffect(()=>{dialog.current?.showModal();void creationDraftRequest<DraftMediaResponse[]>(`/api/creation-drafts/${client.saved.id}/media`).then(setAssets).catch(()=>{});},[client]);

 const background=assets.find(asset=>asset.id===draft.media.backgroundAssetId),src=usePrivateMedia(client.saved.id,background),poster=usePrivateMedia(client.saved.id,background?.kind==="video"?background:undefined,"poster");
 return <dialog ref={dialog} aria-label={c.title} onClose={onClose} className="fixed inset-0 m-auto max-h-[92dvh] w-[min(1100px,96vw)] overflow-y-auto rounded-2xl bg-white dark:bg-ticket-surface p-0 backdrop:bg-black/60"><header className="sticky top-0 z-20 flex items-center justify-between border-b bg-white dark:bg-ticket-surface p-4"><h2 className="font-semibold">{c.title}</h2><button autoFocus type="button" className="min-h-11 rounded-lg border px-4" onClick={()=>dialog.current?.close()}>{c.close}</button></header><div className="creation-preview-hero"><div className="creation-preview-hero-media" aria-hidden="true">{src&&background?<div className="absolute inset-0"><FramedMedia src={src} poster={poster} kind={background.kind} width={background.width??1} height={background.height??1} crop={assetMediaCrop(draft.media,background.id)} alt="" className="h-full w-full"/></div>:null}</div><div className="absolute inset-0 bg-black/55"/><div className="absolute inset-x-0 bottom-0 p-6"><h3 className="break-words text-2xl font-bold leading-tight sm:text-3xl">{content?.title||"—"}</h3>{selection.fallback?<p className="mt-2 text-sm">{c.fallback}: {selection.locale.toUpperCase()}</p>:null}<p className="mt-5">{draft.schedule.startLocal?.replace("T"," · ")}{draft.schedule.endLocal?` – ${draft.schedule.endLocal.replace("T"," · ")}`:""} · {draft.schedule.timezone}</p><p>{content?.address}</p></div></div><div className="grid gap-6 p-6 lg:grid-cols-[1fr_280px]"><EventStory description={content?.description??null} address={content?.address??""} refundConditions={draft.refundsAvailable?content?.refundConditions??null:null} refundsAvailable={draft.refundsAvailable??false} free={draft.selectedMode==="free"} locale={locale}/><aside className="rounded-xl border p-4"><h3 className="font-semibold">{c.tickets}</h3><p className="mt-3">{draft.selectedMode==="free"?draft.free.content[selection.locale]?.name:draft.selectedMode==="paid_general"?draft.paidGeneral.filter(row=>row.active).map(row=>row.content[selection.locale]?.name).join(" · "):draft.paidSeated?.tariffs.filter(row=>row.active).map(row=>row.content[selection.locale]?.name).join(" · ")}</p></aside></div><div className="grid grid-cols-2 gap-3 p-6 sm:grid-cols-3">{draft.media.slots.flatMap(id=>{const asset=assets.find(asset=>asset.id===id);return asset?[<PreviewGallery key={id} draftId={client.saved.id} asset={asset} crop={assetMediaCrop(draft.media,asset.id)} caption={draft.media.captions[id!]?.[selection.locale]??""}/>]:[];})}</div></dialog>;
}
function PreviewGallery({draftId,asset,caption,crop}:{draftId:string;asset:DraftMediaResponse;caption:string;crop:MediaCrop}){const src=usePrivateMedia(draftId,asset),poster=usePrivateMedia(draftId,asset.kind==="video"?asset:undefined,"poster");return src?<figure><FramedMedia src={src} poster={poster} kind={asset.kind} width={asset.width??1} height={asset.height??1} crop={crop} alt={caption} className="aspect-video rounded-xl" controls/></figure>:null;}
