"use client";
import { useEffect,useRef,useState,type PointerEvent } from "react";
import { type DraftMediaResponse,type DraftMediaMutation,type CreationDraftResponse,type EventLocale,assetMediaCrop,type MediaCrop } from "@event-platform/shared-types";
import { DraftAutosave,creationDraftRequest,DraftRequestError } from "../../lib/creation-draft-client";
import { getSession } from "../../app/(auth)/_lib/session";
import { FramedMedia } from "./framed-media";
import { CreationIcon } from "./creation-ui";
import { MediaCropPreview } from "./media-crop-preview";

const words={ru:{add:"Добавить медиа",main:"Обложка",bg:"Фон",hold:"Удерживайте и перетаскивайте медиа для изменения порядка",remove:"Удалить",replace:"Заменить",retry:"Повторить",move:"Переместить",preview:"Предпросмотр",choose:"Выберите изображение или видео",processing:"Обработка",failed:"Ошибка"},en:{add:"Add media",main:"Cover",bg:"Background",hold:"Hold and drag media to reorder",remove:"Remove",replace:"Replace",retry:"Retry",move:"Move",preview:"Preview",choose:"Choose an image or video",processing:"Processing",failed:"Failed"},kk:{add:"Медиа қосу",main:"Мұқаба",bg:"Фон",hold:"Ретін өзгерту үшін медианы басып тұрып сүйреңіз",remove:"Жою",replace:"Ауыстыру",retry:"Қайталау",move:"Жылжыту",preview:"Алдын ала қарау",choose:"Сурет немесе видео таңдаңыз",processing:"Өңдеу",failed:"Қате"}};
const button="creation-button creation-button-small";
function uploadFile(id:string,asset:string,csrf:string,file:File,onProgress:(value:number)=>void){return new Promise<DraftMediaMutation>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("PUT",`/api/creation-drafts/${id}/media/${asset}/upload`);xhr.setRequestHeader("Content-Type",file.type);xhr.setRequestHeader("X-Draft-CSRF",csrf);const session=getSession();if(session)xhr.setRequestHeader("Authorization",`Bearer ${session.tokens.accessToken}`);xhr.timeout=300000;xhr.upload.onprogress=event=>{if(event.lengthComputable)onProgress(Math.round(event.loaded/event.total*100));};xhr.onload=()=>{let body:{code?:string}|DraftMediaMutation;try{body=JSON.parse(xhr.responseText);}catch{reject(new Error("MEDIA_UPLOAD_FAILED"));return;}if(xhr.status>=200&&xhr.status<300)resolve(body as DraftMediaMutation);else reject(new DraftRequestError((body as {code?:string}).code??"MEDIA_UPLOAD_FAILED",xhr.status));};xhr.onerror=()=>reject(new Error("MEDIA_UPLOAD_FAILED"));xhr.ontimeout=()=>reject(new Error("MEDIA_UPLOAD_TIMEOUT"));xhr.send(file);});}
export function usePrivateMedia(draftId:string,asset:DraftMediaResponse|undefined,variant="display"){
  const key=`${asset?.id??""}:${variant}`;
  const [url,setUrl]=useState<{key:string;value:string}|undefined>();
  useEffect(()=>{setUrl(undefined);if(!asset||asset.state!=="ready")return;const abort=new AbortController();let object:string|undefined;const headers=new Headers(),session=getSession();if(session)headers.set("authorization",`Bearer ${session.tokens.accessToken}`);
    void fetch(`/api/creation-drafts/${draftId}/media/${asset.id}/${variant}`,{credentials:"same-origin",headers,cache:"no-store",signal:abort.signal}).then(async response=>{if(!response.ok)throw new Error("MEDIA_NOT_READY");const blob=await response.blob();if(abort.signal.aborted)return;object=URL.createObjectURL(blob);setUrl({key,value:object});}).catch(()=>{});return()=>{abort.abort();if(object)URL.revokeObjectURL(object);};
  },[draftId,asset?.id,asset?.state,variant]);return url?.key===key?url.value:undefined;
}
function Thumbnail({draftId,asset,alt,crop}:{draftId:string;asset:DraftMediaResponse|undefined;alt:string;crop:MediaCrop}){const url=usePrivateMedia(draftId,asset,"thumbnail");return url&&asset?.width&&asset?.height?<FramedMedia src={url} kind="image" width={asset.width} height={asset.height} crop={crop} alt={alt} className="h-full w-full"/>:<span aria-hidden="true" className="grid h-full w-full place-items-center bg-violet-50 dark:bg-ticket-accent-soft"><CreationIcon name="image" /></span>;}
export function MediaGrid({client,locale,contentLocale,onAssetsChange}:{client:DraftAutosave;locale:EventLocale;contentLocale:EventLocale;onAssetsChange?:(assets:DraftMediaResponse[])=>void}){
  const [,tick]=useState(0),[assets,setAssets]=useState<DraftMediaResponse[]>([]),[selected,setSelected]=useState<string|null>(null),[operation,setOperation]=useState(false),[progress,setProgress]=useState<number|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[drag,setDrag]=useState<number|null>(null),[drop,setDrop]=useState<number|null>(null),[uploadDrag,setUploadDrag]=useState(false);
  const input=useRef<HTMLInputElement>(null),choice=useRef<{slot:number;replace?:string;retry?:string}|undefined>(undefined),hold=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),pointer=useRef<{x:number;y:number;active:boolean}|null>(null);
  const draft=client.aggregate,copy=words[locale];const active=assets.find(asset=>asset.id===(selected&&draft.media.slots.includes(selected)?selected:draft.media.cardAssetId??draft.media.backgroundAssetId??draft.media.slots.find(Boolean))),url=usePrivateMedia(client.saved.id,active,active?.kind==="video"?"poster":"display");
  useEffect(()=>{onAssetsChange?.(assets);},[assets,onAssetsChange]);
  const refresh=async()=>setAssets(await creationDraftRequest<DraftMediaResponse[]>(`/api/creation-drafts/${client.saved.id}/media`));
  useEffect(()=>client.subscribe(()=>tick(value=>value+1)),[client]);
  useEffect(()=>{void refresh().catch(reason=>setError(reason.message));},[client,client.saved.revision]);
  useEffect(()=>{if(!assets.some(asset=>["processing","uploading"].includes(asset.state)))return;const timer=setInterval(()=>void refresh().catch(()=>{}),2500);return()=>clearInterval(timer);},[assets,client]);
  async function run(action:()=>Promise<unknown>){if(operation)return;setOperation(true);setError("");try{await action();await refresh();}catch(reason){setError(reason instanceof Error?reason.message:"MEDIA_UPLOAD_FAILED");await refresh().catch(()=>{});}finally{setOperation(false);setProgress(null);}}
  function choose(slot:number,replace?:string,retry?:string){choice.current={slot,...(replace?{replace}:{}),...(retry?{retry}:{})};input.current?.click();}
  async function receive(file:File){const chosen=choice.current;if(!chosen)return;await run(async()=>{
    const response=await client.mutation(saved=>creationDraftRequest<DraftMediaMutation>(chosen.retry?`/api/creation-drafts/${saved.id}/media/${chosen.retry}/retry`:`/api/creation-drafts/${saved.id}/media`,{method:"POST",headers:{"content-type":"application/json","x-draft-csrf":saved.csrfToken},body:JSON.stringify(chosen.retry?{revision:saved.revision}:{revision:saved.revision,slot:chosen.slot,bytes:file.size,contentType:file.type,...(chosen.replace?{replaceAssetId:chosen.replace}:{})})}));
    setSelected(response.asset.id);setProgress(0);await refresh();await uploadFile(client.saved.id,response.asset.id,client.saved.csrfToken,file,setProgress);
  });}
  function reorder(from:number,to:number){if(from===to)return;const slots=[...client.aggregate.media.slots];[slots[from],slots[to]]=[slots[to]!,slots[from]!];client.patch({media:{slots}});setNotice(`${copy.move}: ${from+1} → ${to+1}`);}
  function down(event:PointerEvent<HTMLButtonElement>,index:number){if(operation)return;pointer.current={x:event.clientX,y:event.clientY,active:false};event.currentTarget.setPointerCapture(event.pointerId);hold.current=setTimeout(()=>{if(pointer.current){pointer.current.active=true;setDrag(index);}},event.pointerType==="touch"?350:0);}
  function move(event:PointerEvent<HTMLButtonElement>){const start=pointer.current;if(!start)return;if(!start.active&&Math.hypot(event.clientX-start.x,event.clientY-start.y)>8){clearTimeout(hold.current);pointer.current=null;return;}if(start.active){event.preventDefault();const tile=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>("[data-media-slot]");setDrop(tile?Number(tile.dataset.mediaSlot):null);}}
  function up(){clearTimeout(hold.current);if(drag!==null&&drop!==null)reorder(drag,drop);pointer.current=null;setDrag(null);setDrop(null);}
  const crop=active?assetMediaCrop(draft.media,active.id):{focalX:.5,focalY:.5,zoom:1};
  const extra = {
    ru: { coverLabel: "Обложка карточки", backgroundLabel: "Фон страницы", drop: "Перетащите файл сюда или загрузите с устройства", upload: "Загрузить медиа", formats: "JPG, PNG, WebP · MP4, WebM · до 5 файлов", loading: "Загрузка предпросмотра…", recommended: "Рекомендуемый формат изображения: 16:9.", removeSelected: "Удалить выбранное медиа" },
    en: { coverLabel: "Card cover", backgroundLabel: "Page background", drop: "Drag a file here or upload from your device", upload: "Upload media", formats: "JPG, PNG, WebP · MP4, WebM · up to 5 files", loading: "Loading preview…", recommended: "Recommended image format: 16:9.", removeSelected: "Remove selected media" },
    kk: { coverLabel: "Карточка мұқабасы", backgroundLabel: "Бет фоны", drop: "Файлды осында сүйреңіз немесе құрылғыдан жүктеңіз", upload: "Медиа жүктеу", formats: "JPG, PNG, WebP · MP4, WebM · 5 файлға дейін", loading: "Алдын ала қарау жүктелуде…", recommended: "Ұсынылатын сурет форматы: 16:9.", removeSelected: "Таңдалған медианы жою" },
  }[locale];
  const firstEmpty = draft.media.slots.findIndex(id => id === null), activeSlot = active ? draft.media.slots.indexOf(active.id) : -1;
  const deleteAsset = (id: string) => void run(() => client.mutation(async saved => ({ draft: await creationDraftRequest<CreationDraftResponse>(`/api/creation-drafts/${saved.id}/media/${id}`, { method: "DELETE", headers: { "content-type": "application/json", "x-draft-csrf": saved.csrfToken }, body: JSON.stringify({ revision: saved.revision }) }) })));
  return <div className="creation-fields" aria-label={copy.preview}>
    <p className="creation-media-help">{extra.recommended}</p>
    <input ref={input} type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" className="hidden" onChange={event => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void receive(file); }} />
    <div className="creation-media-editor"><div className="creation-media-preview-column">
    {active && url && active.width && active.height ? <MediaCropPreview key={active.id} src={url} width={active.width} height={active.height} crop={crop} alt={draft.media.captions[active.id]?.[contentLocale] ?? ""} locale={locale} disabled={operation} onChange={next => client.patch({ media: { assetCrops: { [active.id]: next } } })} /> : active ? <div role="status" className="flex aspect-video items-center justify-center rounded-xl bg-violet-50 text-xs text-slate-500 dark:bg-ticket-raised dark:text-ticket-muted">{active.state === "ready" ? extra.loading : active.state === "failed" ? copy.failed : copy.processing}</div> : <div className="creation-upload-zone" data-dragging={uploadDrag} onDragOver={event => { event.preventDefault(); if (!operation && firstEmpty !== -1) setUploadDrag(true); }} onDragLeave={() => setUploadDrag(false)} onDrop={event => { event.preventDefault(); setUploadDrag(false); if (operation || firstEmpty === -1) return; const file = event.dataTransfer.files[0]; if (file) { choice.current = { slot: firstEmpty }; void receive(file); } }}>
      <div className="creation-upload-symbol"><CreationIcon name="image-plus" size={28} /></div><strong>{copy.choose}</strong><p>{extra.drop}</p><button type="button" disabled={operation || firstEmpty === -1} className="creation-button" onClick={() => choose(firstEmpty)}><CreationIcon name="upload" size={17} />{extra.upload}</button><p className="!text-[10px]">{extra.formats}</p>
    </div>}
    {active ? <div className="creation-media-actions creation-media-role-actions" data-image={active.kind === "image"}>
      {active.kind === "image" ? <button disabled={operation || active.state !== "ready"} type="button" className={button} aria-pressed={draft.media.cardAssetId === active.id} onClick={() => client.patch({ media: { cardAssetId: active.id } })}>{extra.coverLabel}</button> : null}
      <button disabled={operation || active.state !== "ready"} type="button" className={button} aria-pressed={draft.media.backgroundAssetId === active.id} onClick={() => client.patch({ media: { backgroundAssetId: active.id } })}>{extra.backgroundLabel}</button>
      <button disabled={operation || active.state === "processing"} type="button" className={`${button} creation-media-icon-button`} aria-label={active.state === "failed" ? copy.retry : copy.replace} title={active.state === "failed" ? copy.retry : copy.replace} onClick={() => choose(activeSlot, active.id, active.state === "failed" ? active.id : undefined)}>
        <svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 7H4m0 0 4-4M4 7l4 4M4 17h16m0 0-4-4m4 4-4 4" /></svg>
      </button>
      <button disabled={operation || active.state === "processing"} type="button" aria-label={extra.removeSelected} title={copy.remove} className={`${button} creation-media-icon-button !text-red-700 dark:!text-ticket-danger`} onClick={() => deleteAsset(active.id)}>
        <svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M3 6h18M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2M5 6l1 14a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1l1-14M10 10v7m4-7v7" /></svg>
      </button>
    </div> : null}
    </div><div className="creation-media-slots">{draft.media.slots.map((id, index) => { const asset = assets.find(item => item.id === id); return <div key={index} data-media-slot={index} data-filled={!!id} className={`creation-media-slot ${drop === index ? "rounded-lg outline-2 outline-violet-500 dark:outline-ticket-accent" : ""}`}>
      <div className="creation-media-tile" data-selected={!!id && active?.id === id} data-empty={!id}>
        {id ? <button type="button" aria-label={`${copy.preview} ${index + 1}`} aria-pressed={active?.id === id} onClick={() => setSelected(id)}><Thumbnail draftId={client.saved.id} asset={asset} alt={draft.media.captions[id]?.[contentLocale] ?? ""} crop={assetMediaCrop(draft.media,id)} /></button> : <button disabled={operation} type="button" aria-label={`${copy.add} ${index + 1}`} onClick={() => choose(index)}><CreationIcon name="plus" size={17} /></button>}
        {id ? <span className="creation-media-slot-number">{draft.media.cardAssetId === id ? copy.main : index + 1}</span> : null}
        {id && asset && asset.state !== "ready" ? <span className="absolute inset-x-0 top-0 bg-white/90 dark:bg-ticket-surface/90 p-1 text-center text-[8px]">{asset.state === "failed" ? copy.failed : copy.processing}</span> : null}
      </div>
      {id ? <button disabled={operation} type="button" className="mt-1 flex min-h-8 w-full touch-none items-center justify-center text-slate-500 dark:text-ticket-muted" aria-label={`${copy.move} ${index + 1}`} onPointerDown={event => down(event, index)} onPointerMove={move} onPointerUp={up} onPointerCancel={() => { clearTimeout(hold.current); pointer.current = null; setDrag(null); setDrop(null); }}>⠿</button> : <span aria-hidden="true" className="creation-media-empty-number">{index + 1}</span>}
    </div>; })}</div></div>
    <p className="creation-media-help">{copy.hold}</p>
    {active?.errorCode && active.state === "failed" ? <p role="status" className="creation-error">{copy.failed}. {copy.retry}</p> : null}
    <p className="sr-only" aria-live="polite">{notice}</p>{progress !== null ? <div role="status"><progress className="w-full accent-violet-600" max={100} value={progress} /><span className="creation-hint">{progress === 100 ? copy.processing : `${progress}%`}</span></div> : null}{error ? <p role="alert" className="creation-error">{error}</p> : null}
  </div>;
}
