"use client";
import { useState } from "react";
import { applyCreationDraftPatch,draftLocaleFields,EVENT_LOCALES,type EventLocale } from "@event-platform/shared-types";
import type { DraftAutosave } from "../../lib/creation-draft-client";
const copy={ru:{found:"На этом устройстве найдены несохранённые изменения.",review:"Показать изменения",restore:"Восстановить изменения",changed:"Сохранённая версия изменилась. Проверьте резервную копию перед заменой соответствующих полей.",apply:"Применить проверенные изменения",dismiss:"Удалить резервную копию",settings:"Настройки билетов, зала или медиа"},en:{found:"Unsaved changes were recovered on this device.",review:"Show recovered changes",restore:"Restore changes",changed:"The saved version has changed. Review the backup before replacing its affected fields.",apply:"Apply reviewed changes",dismiss:"Dismiss backup",settings:"Ticket, hall or media settings"},kk:{found:"Бұл құрылғыда сақталмаған өзгерістер табылды.",review:"Өзгерістерді көрсету",restore:"Өзгерістерді қалпына келтіру",changed:"Сақталған нұсқа өзгерді. Тиісті өрістерді ауыстырмас бұрын көшірмені тексеріңіз.",apply:"Тексерілген өзгерістерді қолдану",dismiss:"Көшірмені алып тастау",settings:"Билет, зал немесе медиа баптаулары"}};
export function RecoveryNotice({client,locale}:{client:DraftAutosave;locale:EventLocale}){
  const [shown,setShown]=useState(false),recovery=client.recoveryCandidate,c=copy[locale];if(!recovery)return null;
  const candidate=applyCreationDraftPatch(client.saved.aggregate,recovery.patch),changed=recovery.baseRevision!==client.saved.revision;
  const texts=EVENT_LOCALES.flatMap(language=>{const before=new Map(draftLocaleFields(client.saved.aggregate,language).map(field=>[field.key,field.text]));return draftLocaleFields(candidate,language).filter(field=>before.get(field.key)!==field.text).map(field=>({language,key:field.key,text:field.text}));});
  return <aside className="space-y-3 rounded-xl border border-amber-300 dark:border-ticket-warning-border bg-amber-50 dark:bg-ticket-warning-soft p-4"><p className="text-sm">{c.found}</p>{changed?<p className="text-sm text-amber-900 dark:text-ticket-warning">{c.changed}</p>:null}<button type="button" className="text-sm text-violet-700 dark:text-ticket-accent" onClick={()=>setShown(!shown)}>{c.review}</button>{shown?<div className="max-h-64 space-y-2 overflow-y-auto rounded-lg bg-white dark:bg-ticket-surface p-3">{texts.map(field=><p key={`${field.language}:${field.key}`} className="whitespace-pre-wrap text-sm"><span className="font-semibold">{({ru:"RU",en:"ENG",kk:"KAZ"})[field.language]}: </span>{field.text||"—"}</p>)}{Object.keys(recovery.patch).some(key=>key!=="content")?<p className="text-sm">{c.settings}</p>:null}</div>:null}<div className="flex flex-wrap gap-2"><button type="button" disabled={client.busy||client.dirty||(changed&&!shown)} className="rounded-lg bg-violet-700 dark:bg-ticket-primary px-3 py-2 text-sm text-white disabled:opacity-50" onClick={()=>client.restoreRecovery(changed&&shown)}>{changed?c.apply:c.restore}</button><button type="button" className="rounded-lg border px-3 py-2 text-sm" onClick={()=>client.dismissRecovery()}>{c.dismiss}</button></div></aside>;
}
