"use client";
import { useEffect,useState } from "react";
import { type CurrencyCapability,type EventLocale,type EventSaleMode,type DraftHallV3 } from "@event-platform/shared-types";
import { useRouter } from "next/navigation";
import { DraftAutosave,creationDraftRequest } from "../../lib/creation-draft-client";
import { CountedField } from "./counted-field";
import { MoneyField } from "./money-field";
import { CreationIcon } from "./creation-ui";
import { CreationSelect } from "./creation-select";
const copy={ru:{modes:["Бесплатно","Платные билеты","Платный зал"],currency:"Валюта",capacity:"Количество мест",name:"Название билета",description:"Описание билета",price:"Цена",add:"Добавить тип билета",remove:"Удалить",hall:"Создать / изменить зал",refund:"Возврат доступен?",yes:"Да",no:"Нет",conditions:"Условия возврата",unavailable:"Возврат денежных средств не предусмотрен.",free:"Бесплатную регистрацию можно отменить без денежного возврата.",relabel:"Суммы будут обозначены в новой валюте без пересчёта курса.",confirm:"Подтвердить",cancel:"Отмена",registration:"Регистрация",savedHall:"Сохранённый зал",tariffs:"Тарифы"},en:{modes:["Free","Paid tickets","Paid hall"],currency:"Currency",capacity:"Capacity",name:"Ticket name",description:"Ticket description",price:"Price",add:"Add ticket type",remove:"Remove",hall:"Create / edit hall",refund:"Refunds available?",yes:"Yes",no:"No",conditions:"Refund conditions",unavailable:"Monetary refunds are not available.",free:"Free registrations can be cancelled without a monetary refund.",relabel:"Amounts will be labelled in the new currency without exchange-rate conversion.",confirm:"Confirm",cancel:"Cancel",registration:"Registration",savedHall:"Saved hall",tariffs:"Tariffs"},kk:{modes:["Тегін","Ақылы билеттер","Ақылы зал"],currency:"Валюта",capacity:"Орын саны",name:"Билет атауы",description:"Билет сипаттамасы",price:"Бағасы",add:"Билет түрін қосу",remove:"Жою",hall:"Зал құру / өзгерту",refund:"Қайтарым бар ма?",yes:"Иә",no:"Жоқ",conditions:"Қайтару шарттары",unavailable:"Ақшалай қайтарым қарастырылмаған.",free:"Тегін тіркелуді ақшалай қайтарымсыз тоқтатуға болады.",relabel:"Бағамды айырбастамай, сомалар жаңа валютамен белгіленеді.",confirm:"Растау",cancel:"Бас тарту",registration:"Тіркелу",savedHall:"Сақталған зал",tariffs:"Тарифтер"}};
const currencyLabels = { ru: { USD: "Доллары", RUB: "Рубли", KZT: "Тенге" }, en: { USD: "US dollars", RUB: "Russian rubles", KZT: "Tenge" }, kk: { USD: "АҚШ доллары", RUB: "Ресей рублі", KZT: "Теңге" } };
const button="creation-button";
export function TicketModes({client,locale,contentLocale,locked=false}:{client:DraftAutosave;locale:EventLocale;contentLocale:EventLocale;locked?:boolean}){
  const [,tick]=useState(0),[currencies,setCurrencies]=useState<CurrencyCapability[]>([]),[pending,setPending]=useState<string|null>(null),[error,setError]=useState("");const router=useRouter(),draft=client.aggregate,words=copy[locale],currency=currencies.find(value=>value.code===draft.currency)??{code:draft.currency,exponent:2};
  useEffect(()=>client.subscribe(()=>tick(value=>value+1)),[client]);useEffect(()=>{void creationDraftRequest<{currencies:CurrencyCapability[]}>("/api/creation-drafts/capabilities").then(value=>setCurrencies(value.currencies)).catch(reason=>setError(reason.message));},[]);
  const extra = {
    ru: { descriptions: ["Регистрация без оплаты", "Один или несколько типов билетов", "Места по схеме зала"], standard: "Входной билет", ticket: "Тип билета", active: "Доступен для продажи", select: "Выберите формат билетов для вашего события.", capacity: "Укажите максимальное количество регистраций.", hall: "Создайте схему зала, добавьте места и назначьте тарифы." },
    en: { descriptions: ["Registration without payment", "One or more ticket types", "Seats on a hall plan"], standard: "General admission", ticket: "Ticket type", active: "Available for sale", select: "Choose the ticket format for your event.", capacity: "Set the maximum number of registrations.", hall: "Create a hall plan, add seats, and assign ticket prices." },
    kk: { descriptions: ["Төлемсіз тіркелу", "Бір немесе бірнеше билет түрі", "Зал жоспары бойынша орындар"], standard: "Кіру билеті", ticket: "Билет түрі", active: "Сатылымда бар", select: "Іс-шараңызға билет форматын таңдаңыз.", capacity: "Тіркелудің ең көп санын көрсетіңіз.", hall: "Зал жоспарын жасап, орындар мен тарифтерді қосыңыз." },
  };
  const mode = (value: EventSaleMode) => { setPending(null); client.patch({ selectedMode: value,
    ...(value === "free" && !draft.free.content[draft.sourceLocale]?.name ? { free: { content: { ...draft.free.content, [draft.sourceLocale]: { ...draft.free.content[draft.sourceLocale], name: copy[draft.sourceLocale].registration } }, amount: 0 } } : {}),
    ...(value === "paid_general" && draft.paidGeneral.length === 0 ? { paidGeneral: [{ id: crypto.randomUUID(), active: true, amount: null, capacity: null, content: { [draft.sourceLocale]: { name: extra[draft.sourceLocale].standard } } }] } : {}),
  }); };
  const capacity = (value: string) => value === "" ? null : Number(value);
  const capacityError = () => setError(locale === "ru" ? "Укажите целое число от 1 до 1 000 000." : locale === "kk" ? "1 мен 1 000 000 арасындағы бүтін санды көрсетіңіз." : "Enter a whole number between 1 and 1,000,000.");
  return <div className="creation-fields">
    <fieldset><legend className="sr-only">{words.modes.join(" / ")}</legend><div className="creation-sale-options">{(["free", "paid_general", "paid_seated"] as const).map((value, index) => <label className="creation-sale-option" data-selected={draft.selectedMode === value} data-locked={locked} key={value}><div className="creation-sale-option-top"><CreationIcon name={(["ticket-check", "ticket2", "armchair"] as const)[index]!} size={17} /><span>{words.modes[index]}</span><input aria-label={words.modes[index]} disabled={locked} type="radio" name="sale-mode" checked={draft.selectedMode === value} onChange={() => mode(value)} /></div><small>{extra[locale].descriptions[index]}</small></label>)}</div></fieldset>
    {!draft.selectedMode ? <p className="creation-hint">{extra[locale].select}</p> : null}
    {draft.selectedMode && draft.selectedMode !== "free" ? <CreationSelect label={words.currency} disabled={locked} value={draft.currency} locale={locale} placeholder={words.currency} options={["USD", "RUB", "KZT"].filter(code => currencies.some(currency => currency.code === code)).map(code => ({ value: code, label: `${currencyLabels[locale][code as "USD" | "RUB" | "KZT"]} · ${code}`, detail: code === "USD" ? "$" : code === "RUB" ? "₽" : "₸" }))} onChange={code => { if (code !== draft.currency) setPending(code); }} /> : null}
    {pending ? <div className="space-y-3 rounded-xl border border-amber-300 dark:border-ticket-warning-border bg-amber-50 dark:bg-ticket-warning-soft p-4" role="alert"><p className="text-sm">{draft.currency} → {pending}. {words.relabel}</p><div className="flex gap-2"><button type="button" className={button} onClick={() => { client.patch({ currency: pending, acknowledgeCurrencyRelabel: true }); setPending(null); }}>{words.confirm}</button><button type="button" className={button} onClick={() => setPending(null)}>{words.cancel}</button></div></div> : null}
    {draft.selectedMode === "free" ? <div className="creation-ticket-fields creation-fields"><div className="creation-two-columns"><label className="creation-field">{words.capacity}<span aria-hidden="true" className="creation-required"> *</span><input aria-label={words.capacity} aria-required className="creation-input" disabled={locked} type="number" min="1" max="1000000" step="1" placeholder="100" value={draft.free.capacity ?? ""} onChange={event => { try { client.patch({ free: { capacity: capacity(event.target.value) } }); setError(""); } catch { capacityError(); } }} /></label><CountedField required={contentLocale === draft.sourceLocale} label={words.name} max={60} value={draft.free.content[contentLocale]?.name ?? ""} onChange={name => client.patch({ free: { content: { ...draft.free.content, [contentLocale]: { ...draft.free.content[contentLocale], name } } } })} /></div><p className="creation-hint !mt-0">{extra[locale].capacity} {words.free}</p></div> : null}
    {draft.selectedMode === "paid_general" ? <div className="creation-fields">{draft.paidGeneral.map((row, index) => {
      const change = (patch: Partial<typeof row>) => client.patch({ paidGeneral: draft.paidGeneral.map(value => value.id === row.id ? { ...value, ...patch } : value) });
      return <fieldset key={row.id} className="creation-ticket-row creation-fields"><legend>{extra[locale].ticket} {index + 1}</legend><CountedField required={contentLocale === draft.sourceLocale} label={words.name} max={60} value={row.content[contentLocale]?.name ?? ""} onChange={name => change({ content: { ...row.content, [contentLocale]: { ...row.content[contentLocale], name } } })} /><CountedField label={words.description} max={300} value={row.content[contentLocale]?.description ?? ""} multiline onChange={description => change({ content: { ...row.content, [contentLocale]: { ...row.content[contentLocale], description } } })} /><div className="creation-two-columns"><MoneyField disabled={locked} label={words.price} value={row.amount} currency={currency} onChange={amount => change({ amount })} /><label className="creation-field">{words.capacity}<span aria-hidden="true" className="creation-required"> *</span><input aria-label={`${words.capacity} ${index + 1}`} aria-required className="creation-input" disabled={locked} type="number" min="1" max="1000000" value={row.capacity ?? ""} onChange={event => { try { change({ capacity: capacity(event.target.value) }); setError(""); } catch { capacityError(); } }} /></label></div><div className="flex items-center justify-between gap-2"><label className="flex items-center gap-2 text-xs"><input disabled={locked} type="checkbox" checked={row.active} onChange={event => change({ active: event.target.checked })} />{extra[locale].active}</label><button type="button" className={`${button} creation-button-small !text-red-700 dark:!text-ticket-danger`} disabled={locked} onClick={() => client.patch({ paidGeneral: draft.paidGeneral.filter(value => value.id !== row.id) })}>{words.remove}</button></div></fieldset>;
    })}<button type="button" className={button} disabled={locked || draft.paidGeneral.length >= 100} onClick={() => client.patch({ paidGeneral: [...draft.paidGeneral, { id: crypto.randomUUID(), active: true, amount: null, capacity: null, content: {} }] })}><CreationIcon name="plus" size={17} />{words.add}</button></div> : null}
    {draft.selectedMode === "paid_seated" ? <div className="creation-ticket-fields creation-fields">{draft.paidSeated ? <><HallThumbnail hall={draft.paidSeated} /><p className="creation-hint">{words.savedHall}: {draft.paidSeated.objects.filter(object => object.type === "seat" && !object.locked).length + draft.paidSeated.objects.filter(object => object.type === "zone" && !object.locked).reduce((sum, object) => sum + object.capacity, 0)} · {words.tariffs}: {draft.paidSeated.tariffs.filter(tariff => tariff.active).map(tariff => `${tariff.content[contentLocale]?.name ?? "—"} (${new Intl.NumberFormat(locale, { style: "currency", currency: draft.currency }).format((tariff.amount ?? 0) / 10 ** currency.exponent)})`).join(", ")}</p></> : <p className="creation-hint !mt-0">{extra[locale].hall}</p>}<button type="button" className={button} disabled={locked} onClick={() => void client.flush().then(() => router.push(`/events/create/hall?draftId=${client.saved.id}&lang=${locale}&contentLocale=${contentLocale}`)).catch(reason => setError(reason.message))}><CreationIcon name="armchair" size={17} />{words.hall}</button></div> : null}
    {draft.selectedMode && draft.selectedMode !== "free" ? <fieldset className="creation-refunds creation-fields"><legend>{words.refund}<span aria-hidden="true" className="creation-required"> *</span></legend><div className="flex gap-5">{[true, false].map(value => <label key={String(value)} className="flex gap-2 text-sm"><input type="radio" name="refund-available" checked={draft.refundsAvailable === value} onChange={() => client.patch({ refundsAvailable: value })} />{value ? words.yes : words.no}</label>)}</div>{draft.refundsAvailable ? <CountedField required={contentLocale === draft.sourceLocale} label={words.conditions} max={2000} multiline value={draft.content[contentLocale]?.refundConditions ?? ""} onChange={refundConditions => client.patch({ content: { [contentLocale]: { ...draft.content[contentLocale], refundConditions } } })} /> : draft.refundsAvailable === false ? <p className="creation-hint">{words.unavailable}</p> : null}</fieldset> : null}
    {error ? <p role="alert" className="creation-error">{error}</p> : null}
  </div>;
}

function HallThumbnail({hall}:{hall:DraftHallV3}){return <svg role="img" aria-label="Hall preview" className="h-40 w-full rounded-xl border border-slate-200 dark:border-ticket-border bg-white dark:bg-ticket-surface" viewBox={`0 0 ${hall.room.widthM} ${hall.room.heightM}`}><rect width={hall.room.widthM} height={hall.room.heightM} fill="#f8f7fc" stroke="#cbc7d4" strokeWidth=".1"/>{hall.objects.map(object=><g key={object.id} transform={`translate(${object.x} ${object.y}) rotate(${object.rotation})`}>{object.type==="seat"?<circle r=".22" fill={object.color}/>:<rect x={-object.width/2} y={-object.height/2} width={object.width} height={object.height} rx={object.type==="table_round"?object.width/2:.05} fill={object.color} opacity={object.type==="zone"?.3:1}/>}</g>)}</svg>;}
