"use client";
import { useEffect,useState } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import Link from "next/link";
import { useLocale } from "../../../../components/locale-provider";
import { isLocale } from "../../../../lib/locale";
import { creationContinuation,publicationEditor,resumePublication } from "../../../../lib/creation-publication-client";
import { getSession } from "../../../(auth)/_lib/session";
const words={ru:{pending:"Публикуем ваше событие…",blocked:"По текущим правилам требуется одобрение организатора. Черновик сохранён.",review:"Черновик или намерение публикации изменились либо истекли. Проверьте его и нажмите «Опубликовать» снова.",failed:"Не удалось завершить публикацию. Черновик сохранён.",back:"Вернуться к черновику",retry:"Повторить",login:"Войти и продолжить"},en:{pending:"Publishing your event…",blocked:"The current policy requires organizer approval. Your draft is saved.",review:"The draft or publication intent changed or expired. Review it and click Publish again.",failed:"Publication could not finish. Your draft is saved.",back:"Return to draft",retry:"Retry",login:"Sign in and continue"},kk:{pending:"Іс-шара жарияланып жатыр…",blocked:"Қазіргі ереже бойынша ұйымдастырушыға мақұлдау қажет. Жоба сақталған.",review:"Жоба немесе жариялау ниеті өзгерген не мерзімі өткен. Тексеріп, қайта жариялаңыз.",failed:"Жариялау аяқталмады. Жоба сақталған.",back:"Жобаға оралу",retry:"Қайталау",login:"Кіріп, жалғастыру"}};
export function PublicationContinuation(){const params=useSearchParams(),router=useRouter(),locale=useLocale(),contentLocale=isLocale(params.get("contentLocale"))?params.get("contentLocale") as typeof locale:locale,id=params.get("draftId")??"",intentId=params.get("intentId")??"",[error,setError]=useState(""),[attempt,setAttempt]=useState(0),c=words[locale];
 const valid=/^[0-9a-f-]{36}$/i.test(id)&&/^[0-9a-f-]{36}$/i.test(intentId);
 useEffect(()=>{if(!valid||!getSession()){setError("SESSION_REQUIRED");return;}let live=true;setError("");void resumePublication(id,intentId).then(result=>{if(live)router.replace(publicationEditor(result,locale,contentLocale));}).catch(reason=>{if(live)setError(reason.message);});return()=>{live=false;};},[id,intentId,locale,contentLocale,router,valid,attempt]);
 const stale=["PUBLISH_INTENT_STALE","PUBLISH_INTENT_EXPIRED","DRAFT_EXPIRED"].includes(error);
 return <main className="mx-auto max-w-xl space-y-5 px-4 py-16"><h1 role={error?"alert":"status"} className="text-xl font-semibold">{!error?c.pending:error==="ORGANIZER_APPROVAL_REQUIRED"?c.blocked:stale?c.review:c.failed}</h1>{error?<div className="flex flex-wrap gap-3"><Link className="rounded-xl border px-4 py-3" href={`/events/create?draftId=${id}&lang=${locale}&contentLocale=${contentLocale}`}>{c.back}</Link>{error==="SESSION_REQUIRED"&&valid?<Link className="rounded-xl bg-violet-700 dark:bg-ticket-primary px-4 py-3 text-white" href={`/login?lang=${locale}&returnTo=${encodeURIComponent(creationContinuation(id,intentId,locale,contentLocale))}`}>{c.login}</Link>:!stale&&error!=="ORGANIZER_APPROVAL_REQUIRED"?<button className="rounded-xl bg-violet-700 dark:bg-ticket-primary px-4 py-3 text-white" onClick={()=>setAttempt(value=>value+1)}>{c.retry}</button>:null}</div>:null}</main>;
}
