import type { EventLocale } from "@event-platform/shared-types";

const ru = {
  defaultCurrency: "Валюта по умолчанию", defaultCurrencyHint: "Для отображения цен в афише", currencyRatesHint: "RUB и USD доступны при наличии курса",
  account: "Личный кабинет", tickets: "Билеты и заказы", profile: "Личные данные и настройки", notifications: "Telegram-бот и уведомления",
  ticketsHint: "Ваши предстоящие события, покупки и билеты — в одном месте.", profileHint: "Управляйте контактами профиля и способами входа в аккаунт.", notificationsHint: "Настройте, какие сообщения получать, и просматривайте входящие в кабинете.",
  profileNav: "Данные и настройки", notificationsNav: "Telegram и уведомления", organizer: "Для организатора", organizerHint: "Управляйте событиями и продажами в отдельном кабинете.", help: "Помощь и поддержка", logout: "Выйти из аккаунта",
  noContacts: "Контактный email и телефон не указаны", telegramLinked: "Telegram подключён", noUpcoming: "Пока нет предстоящих событий", emptyTicketsHint: "Выберите событие и оформите билет. После покупки он появится здесь.", findEvent: "Найти событие", myOrders: "Мои заказы", noOrders: "Заказов пока нет", ordersHint: "Здесь будут детали покупок и статус оплаты ваших билетов.", ticketHelp: "Купили билет, но не видите его?", contactSupport: "Связаться с поддержкой",
  notProvided: "Не указан", chooseCity: "Выберите город", cityHint: "Для поиска событий рядом с вами.", optional: "Все поля необязательные", contactsHint: "Контакты для профиля. Они не меняют ваши способы входа.", contactsTitle: "Контакты ≠ способ входа", contactsMissing: "Контактный email пока не указан. Для входа уже подключён другой email:", contactsPresent: "Контактный email и email для входа хранятся отдельно. Подключённый email для входа:", noLoginEmail: "Email для входа пока не подключён.", separateVerification: "Новый способ входа нужно отдельно подтвердить кодом.", confirmation: "Подтверждение контакта", verificationHint: "Отправим код на указанный email. После подтверждения вы сможете использовать его для входа.", phoneHint: "Чтобы подключить номер, выберите «Телефон».", connectPhone: "Подключить телефон", connectTelegram: "Подключить Telegram", connectGoogle: "Подключить Google", googleUnavailable: "Google сейчас недоступен. Используйте другой способ входа.",
  botTitle: "Подключите Telegram-бота", unlinked: "Не подключён", settingsHint: "Выберите сообщения, которые хотите получать.", marketingHint: "Подборки событий и специальные предложения", inboxErrorHint: "Сейчас сервер недоступен. Попробуйте ещё раз. Ваши настройки уведомлений не изменились.", retry: "Повторить попытку", close: "Закрыть", supportHint: "Проверьте, что вы вошли в аккаунт, с которого покупали билет. В истории оплат найдите заказ: для оплаченного заказа можно написать организатору.", openPayments: "Открыть историю оплат", openSettings: "Проверить способы входа", saveFailed: "Не удалось сохранить настройки. Попробуйте ещё раз.",
} as const;
type RedesignCopy = { [K in keyof typeof ru]: string };
export const ACCOUNT_REDESIGN_COPY: Record<EventLocale, RedesignCopy> = {
  ru,
  kk: {
    defaultCurrency: "Әдепкі валюта", defaultCurrencyHint: "Афишадағы бағаларды көрсету үшін", currencyRatesHint: "RUB және USD бағам болғанда қолжетімді",
    account: "Жеке кабинет", tickets: "Билеттер мен тапсырыстар", profile: "Жеке деректер мен баптаулар", notifications: "Telegram-бот және хабарландырулар", ticketsHint: "Алдағы іс-шаралар, сатып алулар мен билеттер — бір жерде.", profileHint: "Профильдің байланыс деректері мен кіру тәсілдерін басқарыңыз.", notificationsHint: "Хабарларды таңдап, кабинеттегі кіріс хабарларды қараңыз.", profileNav: "Деректер мен баптаулар", notificationsNav: "Telegram және хабарлар", organizer: "Ұйымдастырушыға", organizerHint: "Іс-шаралар мен сатылымдарды жеке кабинетте басқарыңыз.", help: "Көмек және қолдау", logout: "Аккаунттан шығу", noContacts: "Байланыс email мен телефон көрсетілмеген", telegramLinked: "Telegram қосылған", noUpcoming: "Алдағы іс-шаралар әзірге жоқ", emptyTicketsHint: "Іс-шараны таңдап, билет алыңыз. Сатып алғаннан кейін ол осында пайда болады.", findEvent: "Іс-шара табу", myOrders: "Тапсырыстарым", noOrders: "Тапсырыстар әзірге жоқ", ordersHint: "Билеттеріңіздің сатып алу деректері мен төлем күйі осында болады.", ticketHelp: "Билет сатып алдыңыз, бірақ көрінбей ме?", contactSupport: "Қолдауға жүгіну", notProvided: "Көрсетілмеген", chooseCity: "Қаланы таңдаңыз", cityHint: "Жақын маңдағы іс-шараларды іздеу үшін.", optional: "Барлық өріс міндетті емес", contactsHint: "Профильге арналған байланыстар. Олар кіру тәсілдерін өзгертпейді.", contactsTitle: "Байланыс ≠ кіру тәсілі", contactsMissing: "Байланыс email көрсетілмеген. Кіру үшін басқа email қосылған:", contactsPresent: "Байланыс email мен кіру email бөлек сақталады. Кіру үшін қосылған email:", noLoginEmail: "Кіру email әлі қосылмаған.", separateVerification: "Жаңа кіру тәсілін кодпен бөлек растау қажет.", confirmation: "Байланысты растау", verificationHint: "Көрсетілген email-ге код жібереміз. Растағаннан кейін оны кіру үшін пайдалана аласыз.", phoneHint: "Нөмір қосу үшін «Телефон» таңдаңыз.", connectPhone: "Телефон қосу", connectTelegram: "Telegram қосу", connectGoogle: "Google қосу", googleUnavailable: "Google қазір қолжетімсіз. Басқа кіру тәсілін пайдаланыңыз.", botTitle: "Telegram-ботты қосыңыз", unlinked: "Қосылмаған", settingsHint: "Алғыңыз келетін хабарларды таңдаңыз.", marketingHint: "Іс-шаралар топтамалары мен арнайы ұсыныстар", inboxErrorHint: "Сервер қазір қолжетімсіз. Қайта көріңіз. Хабарландыру баптаулары өзгерген жоқ.", retry: "Қайта көру", close: "Жабу", supportHint: "Билет сатып алған аккаунтқа кіргеніңізді тексеріңіз. Төлемдер тарихынан тапсырысты табыңыз: төленген тапсырыс бойынша ұйымдастырушыға жазуға болады.", openPayments: "Төлемдер тарихын ашу", openSettings: "Кіру тәсілдерін тексеру", saveFailed: "Баптауларды сақтау мүмкін болмады. Қайта көріңіз.",
  },
  en: {
    defaultCurrency: "Default currency", defaultCurrencyHint: "For prices in the event catalog", currencyRatesHint: "RUB and USD require exchange rates",
    account: "My account", tickets: "Tickets and orders", profile: "Personal details and settings", notifications: "Telegram bot and notifications", ticketsHint: "Your upcoming events, purchases and tickets — in one place.", profileHint: "Manage your profile contacts and account sign-in methods.", notificationsHint: "Choose which messages to receive and view your account inbox.", profileNav: "Details and settings", notificationsNav: "Telegram and notifications", organizer: "For organizers", organizerHint: "Manage events and sales in your organizer dashboard.", help: "Help and support", logout: "Sign out", noContacts: "Contact email and phone not provided", telegramLinked: "Telegram connected", noUpcoming: "No upcoming events yet", emptyTicketsHint: "Choose an event and get a ticket. It will appear here after purchase.", findEvent: "Find an event", myOrders: "My orders", noOrders: "No orders yet", ordersHint: "Your purchase details and ticket payment status will appear here.", ticketHelp: "Bought a ticket but cannot see it?", contactSupport: "Get help", notProvided: "Not provided", chooseCity: "Choose a city", cityHint: "For finding events near you.", optional: "All fields are optional", contactsHint: "Contacts for your profile. They do not change your sign-in methods.", contactsTitle: "Contacts ≠ sign-in method", contactsMissing: "No contact email yet. A different email is already connected for sign-in:", contactsPresent: "Contact and sign-in emails are stored separately. Your connected sign-in email:", noLoginEmail: "No sign-in email connected yet.", separateVerification: "Verify each new sign-in method separately with a code.", confirmation: "Contact verification", verificationHint: "We will send a code to this email. After verification you can use it to sign in.", phoneHint: "To connect a number, choose Phone.", connectPhone: "Connect phone", connectTelegram: "Connect Telegram", connectGoogle: "Connect Google", googleUnavailable: "Google is currently unavailable. Use another sign-in method.", botTitle: "Connect the Telegram bot", unlinked: "Not connected", settingsHint: "Choose which messages you want to receive.", marketingHint: "Event picks and special offers", inboxErrorHint: "The server is currently unavailable. Try again. Your notification settings have not changed.", retry: "Try again", close: "Close", supportHint: "Check that you are signed in to the account used for your purchase. Find the order in payment history: paid orders let you message the organizer.", openPayments: "Open payment history", openSettings: "Check sign-in methods", saveFailed: "Could not save settings. Try again.",
  },
};
