import type { EventLocale } from "@event-platform/shared-types";

interface AnalyticsCopy {
  navigation: string; back: string; analytics: string; eventAnalytics: string; preparing: string; financialCsv: string; ordersCsv: string;
  currentState: string; inventory: string; asOf: string; soldSeats: string; availableNow: string; issuedTickets: string; active: string; used: string;
  tables: string; held: string; available: string; attendance: string; groupScans: string; cancellations: string; tickets: string; bookings: string;
  refundRequests: string; refundNote: string; grossReceived: string; depositsReceived: string; periodSales: string; revenueTrend: string;
  from: string; to: string; grouping: string; byDay: string; byHour: string; apply: string; downloadFailed: string;
  separateCurrency: string; currency: string; unavailable: string; noRevenue: string; allTime: string; unknownCurrency: string;
  periodTotals: string; receivedInPeriod: string; depositsInPeriod: string; depositsIncluded: string; selectedPeriod: string;
  historyUnavailable: string; currencyHistoryUnavailable: string; noPeriodRevenue: string; intervalAmounts: string; chartLabel: string;
  unknownSkipped: string; byTicketType: string; ticketTypeNote: string; noTypeSales: string; intervalData: string; timezone: string; timezoneNote: string;
  period: string; received: string; refunds: string; deposits: string; seats: string; incompleteHistory: string;
  missingSettlement: string; missingRefund: string; missingTypeRevenue: string; loadFailed: string; retry: string;
  analyticsLoading: string; reportLoading: string; rangeRequired: string; rangeOrder: string; maximumPeriod: string; days: string; unknownError: string;
}
export const ANALYTICS_COPY: Record<EventLocale, AnalyticsCopy> = {
  ru: { navigation: "Навигация по мероприятию", back: "Управление событием", analytics: "Аналитика", eventAnalytics: "Аналитика мероприятия", preparing: "Готовим…", financialCsv: "Финансовый CSV", ordersCsv: "Заказы CSV", currentState: "Текущее состояние", inventory: "Инвентарь и посещаемость", asOf: "На", soldSeats: "Продано мест", availableNow: "Доступно сейчас", issuedTickets: "Выдано билетов", active: "Активных", used: "Использовано", tables: "Столы", held: "В резерве", available: "Доступно", attendance: "Посещаемость", groupScans: "Сканирований групповых пропусков", cancellations: "Отмены", tickets: "Билеты", bookings: "Брони", refundRequests: "Запросы возврата", refundNote: "Запросы не равны завершённым возвратам", grossReceived: "Получено всего", depositsReceived: "Получено депозитов", periodSales: "Продажи за период", revenueTrend: "Динамика поступлений", from: "С даты", to: "По дату", grouping: "Группировка", byDay: "По дням", byHour: "По часам", apply: "Применить", downloadFailed: "Не удалось скачать файл", separateCurrency: "Денежные показатели показаны отдельно по каждой валюте.", currency: "Валюта", unavailable: "Недоступно", noRevenue: "Нет поступлений", allTime: "За всё время", unknownCurrency: "Валюта не определена", periodTotals: "Итоги за выбранный период", receivedInPeriod: "Получено за период", depositsInPeriod: "Депозиты за период", depositsIncluded: "Входят в полученную сумму", selectedPeriod: "За выбранный период", historyUnavailable: "Исторические поступления за выбранный период недоступны.", currencyHistoryUnavailable: "Валюта и история поступлений за выбранный период недоступны.", noPeriodRevenue: "За выбранный период поступлений нет", intervalAmounts: "Суммы за каждый интервал", chartLabel: "График поступлений", unknownSkipped: "Периоды с неизвестными суммами пропущены.", byTicketType: "По типам билетов", ticketTypeNote: "Проданные места, без оценки выручки по тарифу", noTypeSales: "Продаж по типам билетов пока нет.", intervalData: "Данные по интервалам", timezone: "Часовой пояс", timezoneNote: "«Недоступно» означает неполную историческую запись; пустой интервал с полным учётом означает 0.", period: "Период", received: "Получено", refunds: "Возвраты", deposits: "Депозиты", seats: "Места", incompleteHistory: "История заполнена не полностью", missingSettlement: "У части старых платежей нет точного времени зачисления", missingRefund: "Для старых возвратов не сохранилась подтверждённая сумма или дата", missingTypeRevenue: "Историческая выручка по типам билетов недоступна", loadFailed: "Не удалось загрузить аналитику", retry: "Повторить", analyticsLoading: "Загрузка аналитики", reportLoading: "Загрузка отчёта", rangeRequired: "Выберите начало и конец периода.", rangeOrder: "Дата окончания должна быть не раньше даты начала.", maximumPeriod: "Максимальный период", days: "дней", unknownError: "Неизвестная ошибка" },
  kk: { navigation: "Іс-шара навигациясы", back: "Іс-шараны басқару", analytics: "Аналитика", eventAnalytics: "Іс-шара аналитикасы", preparing: "Дайындалуда…", financialCsv: "Қаржылық CSV", ordersCsv: "Тапсырыстар CSV", currentState: "Ағымдағы жағдай", inventory: "Орындар мен келушілер", asOf: "Уақыты", soldSeats: "Сатылған орындар", availableNow: "Қазір қолжетімді", issuedTickets: "Берілген билеттер", active: "Белсенді", used: "Пайдаланылған", tables: "Үстелдер", held: "Резервте", available: "Қолжетімді", attendance: "Келушілер", groupScans: "Топтық рұқсат скандары", cancellations: "Бас тартулар", tickets: "Билеттер", bookings: "Брондар", refundRequests: "Қайтару өтініштері", refundNote: "Өтініш саны аяқталған қайтарым санына тең емес", grossReceived: "Жалпы түскен", depositsReceived: "Түскен депозиттер", periodSales: "Кезеңдегі сатылым", revenueTrend: "Түсім динамикасы", from: "Бастап", to: "Дейін", grouping: "Топтау", byDay: "Күн бойынша", byHour: "Сағат бойынша", apply: "Қолдану", downloadFailed: "Файлды жүктеу мүмкін болмады", separateCurrency: "Ақша көрсеткіштері әр валюта үшін бөлек көрсетіледі.", currency: "Валюта", unavailable: "Қолжетімсіз", noRevenue: "Түсім жоқ", allTime: "Барлық уақыт", unknownCurrency: "Валюта анықталмады", periodTotals: "Таңдалған кезең қорытындысы", receivedInPeriod: "Кезеңде түскен", depositsInPeriod: "Кезеңдегі депозиттер", depositsIncluded: "Жалпы түсімге кіреді", selectedPeriod: "Таңдалған кезең", historyUnavailable: "Таңдалған кезеңнің тарихи түсімі қолжетімсіз.", currencyHistoryUnavailable: "Валюта мен тарихи түсім қолжетімсіз.", noPeriodRevenue: "Таңдалған кезеңде түсім жоқ", intervalAmounts: "Әр аралықтағы сома", chartLabel: "Түсім графигі", unknownSkipped: "Белгісіз сомалары бар кезеңдер көрсетілмеді.", byTicketType: "Билет түрлері бойынша", ticketTypeNote: "Сатылған орындар, тариф бойынша түсімді бағаламай", noTypeSales: "Билет түрлері бойынша сатылым жоқ.", intervalData: "Аралық деректері", timezone: "Уақыт белдеуі", timezoneNote: "«Қолжетімсіз» толық емес тарихи жазбаны білдіреді; толық есептелген бос аралық 0 болады.", period: "Кезең", received: "Түскен", refunds: "Қайтарымдар", deposits: "Депозиттер", seats: "Орындар", incompleteHistory: "Тарих толық емес", missingSettlement: "Кейбір ескі төлемдердің түскен уақыты белгісіз", missingRefund: "Ескі қайтарымдардың расталған сомасы немесе күні сақталмаған", missingTypeRevenue: "Билет түрлері бойынша тарихи түсім қолжетімсіз", loadFailed: "Аналитиканы жүктеу мүмкін болмады", retry: "Қайталау", analyticsLoading: "Аналитика жүктелуде", reportLoading: "Есеп жүктелуде", rangeRequired: "Кезеңнің басы мен соңын таңдаңыз.", rangeOrder: "Аяқталу күні басталу күнінен ерте болмауы керек.", maximumPeriod: "Ең ұзақ кезең", days: "күн", unknownError: "Белгісіз қате" },
  en: { navigation: "Event navigation", back: "Event management", analytics: "Analytics", eventAnalytics: "Event analytics", preparing: "Preparing…", financialCsv: "Financial CSV", ordersCsv: "Orders CSV", currentState: "Current state", inventory: "Inventory and attendance", asOf: "As of", soldSeats: "Seats sold", availableNow: "Available now", issuedTickets: "Tickets issued", active: "Active", used: "Used", tables: "Tables", held: "Held", available: "Available", attendance: "Attendance", groupScans: "Group pass scans", cancellations: "Cancellations", tickets: "Tickets", bookings: "Bookings", refundRequests: "Refund requests", refundNote: "Requests are not the same as completed refunds", grossReceived: "Total received", depositsReceived: "Deposits received", periodSales: "Period sales", revenueTrend: "Revenue trend", from: "From", to: "To", grouping: "Group by", byDay: "By day", byHour: "By hour", apply: "Apply", downloadFailed: "Could not download the file", separateCurrency: "Money figures are shown separately for each currency.", currency: "Currency", unavailable: "Unavailable", noRevenue: "No revenue", allTime: "All time", unknownCurrency: "Currency unknown", periodTotals: "Selected period totals", receivedInPeriod: "Received in period", depositsInPeriod: "Deposits in period", depositsIncluded: "Included in total received", selectedPeriod: "Selected period", historyUnavailable: "Historical revenue for the selected period is unavailable.", currencyHistoryUnavailable: "Currency and historical revenue are unavailable.", noPeriodRevenue: "No revenue in the selected period", intervalAmounts: "Amounts for each interval", chartLabel: "Revenue chart", unknownSkipped: "Intervals with unknown amounts are omitted.", byTicketType: "By ticket type", ticketTypeNote: "Seats sold, without estimating revenue by rate", noTypeSales: "No sales by ticket type yet.", intervalData: "Interval data", timezone: "Time zone", timezoneNote: "“Unavailable” means an incomplete historical record; an empty interval with complete accounting means 0.", period: "Period", received: "Received", refunds: "Refunds", deposits: "Deposits", seats: "Seats", incompleteHistory: "History is incomplete", missingSettlement: "Some older payments lack an exact settlement time", missingRefund: "Confirmed amount or date is missing for older refunds", missingTypeRevenue: "Historical revenue by ticket type is unavailable", loadFailed: "Could not load analytics", retry: "Retry", analyticsLoading: "Loading analytics", reportLoading: "Loading report", rangeRequired: "Choose a start and end date.", rangeOrder: "End date must not be before start date.", maximumPeriod: "Maximum period", days: "days", unknownError: "Unknown error" },
};
