import type { EventLocale } from "@event-platform/shared-types";

interface CheckoutCopy {
  deposit: string; tickets: string; choose: string; plan: string; left: string; quantity: string; decrease: string; increase: string; table: string; places: string; wholeTable: string; seat: string; row: string; selectedSeats: string; clear: string; noOptions: string; yourChoice: string; nothing: string; total: string; approximately: string; paymentIn: string; invalidSelection: string; combinedRefund: string; refresh: string; pay: string; guestHint: string; openPlan: string; unavailable: string; quick: string; loading: string; depositExplanation: string; fullPaymentExplanation: string; acceptTerms: string; created: string; continuePayment: string; failed: string;
  emailTickets: string; verifiedEmail: string; useOther: string; useVerified: string; willSend: string; recipientEmail: string; codeSent: string; change: string; verificationCode: string; resendIn: string; resend: string; wait: string; getCode: string; confirmEmail: string; emailFailed: string;
}

export const CHECKOUT_COPY: Record<EventLocale, CheckoutCopy> = {
  ru: {
    deposit: "Бронирование по депозиту", tickets: "Билеты на событие", choose: "Выберите билеты и места", plan: "Выберите места на схеме ↓", left: "осталось", quantity: "Количество", decrease: "Уменьшить", increase: "Увеличить", table: "Стол", places: "мест", wholeTable: "стол целиком", seat: "место", row: "Ряд", selectedSeats: "Места на схеме", clear: "Очистить", noOptions: "Доступные варианты скоро появятся.", yourChoice: "Ваш выбор", nothing: "Ничего не выбрано", total: "Итого к оплате", approximately: "Ориентировочно", paymentIn: "оплата в", invalidSelection: "Проверьте доступность, валюту и количество (не более 10 билетов и мест за раз).", combinedRefund: "Для комбинированного заказа возврат оформляется целиком через организатора.", refresh: "Обновить доступность", pay: "Перейти к оплате", guestHint: "Личный кабинет не обязателен. Подтвердите Telegram или email, чтобы получить билеты.", openPlan: "Открыть схему зала ↓", unavailable: "Недоступно", quick: "Продолжить без аккаунта", loading: "Загрузка…", depositExplanation: "Сейчас оплачивается только депозит. Полная стоимость, если показана, указана справочно.", fullPaymentExplanation: "Сейчас оплачивается полная стоимость.", acceptTerms: "Я принимаю условия оплаты и отмены", created: "Заказ создан. Перейдите к оплате до истечения срока.", continuePayment: "Перейти к оплате", failed: "Не удалось создать заказ.",
    emailTickets: "Отправить билеты на email", verifiedEmail: "Подтверждённый email", useOther: "Использовать другой", useVerified: "Использовать подтверждённый email", willSend: "Билеты будут отправлены после подтверждения оплаты. Получатель не получит доступ к аккаунту.", recipientEmail: "Email получателя", codeSent: "Код отправлен на", change: "Изменить", verificationCode: "Код подтверждения", resendIn: "Новый код через", resend: "Отправить новый код", wait: "Подождите…", getCode: "Получить код", confirmEmail: "Подтвердить email", emailFailed: "Не удалось отправить или проверить код."
  },
  kk: {
    deposit: "Депозитпен брондау", tickets: "Іс-шара билеттері", choose: "Билеттер мен орындарды таңдаңыз", plan: "Сызбадан орын таңдаңыз ↓", left: "қалды", quantity: "Саны", decrease: "Азайту", increase: "Көбейту", table: "Үстел", places: "орын", wholeTable: "толық үстел", seat: "орын", row: "Қатар", selectedSeats: "Сызбадағы орындар", clear: "Тазалау", noOptions: "Қолжетімді нұсқалар жақында пайда болады.", yourChoice: "Сіздің таңдауыңыз", nothing: "Ештеңе таңдалмады", total: "Төленетін сома", approximately: "Шамамен", paymentIn: "төлем валютасы", invalidSelection: "Қолжетімділікті, валютаны және санын тексеріңіз (бір тапсырыста 10 билет пен орыннан артық емес).", combinedRefund: "Аралас тапсырыстың қайтарымы ұйымдастырушы арқылы толық рәсімделеді.", refresh: "Қолжетімділікті жаңарту", pay: "Төлемге өту", guestHint: "Жеке кабинет міндетті емес. Билеттерді алу үшін Telegram не email растаңыз.", openPlan: "Зал сызбасын ашу ↓", unavailable: "Қолжетімсіз", quick: "Тіркелмей жалғастыру", loading: "Жүктелуде…", depositExplanation: "Қазір тек депозит төленеді. Толық құн көрсетілсе, ол ақпарат үшін ғана берілген.", fullPaymentExplanation: "Қазір толық құн төленеді.", acceptTerms: "Төлем және бас тарту шарттарымен келісемін", created: "Тапсырыс жасалды. Уақыты аяқталмай төлемге өтіңіз.", continuePayment: "Төлемге өту", failed: "Тапсырыс жасау мүмкін болмады.",
    emailTickets: "Билеттерді email арқылы жіберу", verifiedEmail: "Расталған email", useOther: "Басқасын пайдалану", useVerified: "Расталған email пайдалану", willSend: "Билеттер төлем расталған соң жіберіледі. Алушы аккаунтқа кіре алмайды.", recipientEmail: "Алушының email мекенжайы", codeSent: "Код жіберілді:", change: "Өзгерту", verificationCode: "Растау коды", resendIn: "Жаңа кодқа дейін", resend: "Жаңа код жіберу", wait: "Күте тұрыңыз…", getCode: "Код алу", confirmEmail: "Email растау", emailFailed: "Кодты жіберу немесе тексеру мүмкін болмады."
  },
  en: {
    deposit: "Deposit booking", tickets: "Event tickets", choose: "Choose tickets and seats", plan: "Choose seats on the map ↓", left: "left", quantity: "Quantity", decrease: "Decrease", increase: "Increase", table: "Table", places: "seats", wholeTable: "whole table", seat: "seat", row: "Row", selectedSeats: "Selected seats", clear: "Clear", noOptions: "Available options will appear soon.", yourChoice: "Your selection", nothing: "Nothing selected", total: "Total due", approximately: "Approximately", paymentIn: "payment in", invalidSelection: "Check availability, currency, and quantity (up to 10 tickets and seats per order).", combinedRefund: "Refunds for combined orders are processed in full through the organizer.", refresh: "Refresh availability", pay: "Proceed to payment", guestHint: "An account is optional. Verify Telegram or email to receive your tickets.", openPlan: "Open venue map ↓", unavailable: "Unavailable", quick: "Continue without account", loading: "Loading…", depositExplanation: "Only the deposit is due now. Any full price shown is for reference.", fullPaymentExplanation: "The full price is due now.", acceptTerms: "I accept the payment and cancellation terms", created: "Order created. Proceed to payment before it expires.", continuePayment: "Proceed to payment", failed: "Could not create the order.",
    emailTickets: "Send tickets by email", verifiedEmail: "Verified email", useOther: "Use another", useVerified: "Use verified email", willSend: "Tickets will be sent after payment is confirmed. The recipient will not gain account access.", recipientEmail: "Recipient email", codeSent: "Code sent to", change: "Change", verificationCode: "Verification code", resendIn: "New code in", resend: "Send new code", wait: "Please wait…", getCode: "Get code", confirmEmail: "Verify email", emailFailed: "Could not send or verify the code."
  }
};
