import type { CreationDraftResponse,CreationPublication,CreationPublishIntent,EventLocale } from "@event-platform/shared-types";
import { creationDraftRequest,finishPublishedDraft,type DraftAutosave } from "./creation-draft-client";
import { getSession,updateSessionUser } from "../app/(auth)/_lib/session";
const resumes=new Map<string,Promise<CreationPublication>>();
export function creationContinuation(id:string,intentId:string,locale:EventLocale,contentLocale:EventLocale){return `/events/create/continue?draftId=${encodeURIComponent(id)}&intentId=${encodeURIComponent(intentId)}&lang=${locale}&contentLocale=${contentLocale}`;}
export function publicationEditor(result:Pick<CreationPublication,"eventId">,locale:EventLocale,contentLocale:EventLocale){return `/organizer/events/${result.eventId}/edit?published=1&lang=${locale}&contentLocale=${contentLocale}`;}
export async function preparePublication(client:DraftAutosave){const saved=await client.flush();const intent=await creationDraftRequest<CreationPublishIntent>(`/api/creation-drafts/${saved.id}/publish-intent`,{method:"POST",headers:{"content-type":"application/json","x-draft-csrf":saved.csrfToken},body:JSON.stringify({revision:saved.revision})});if(client.dirty||client.saved.revision!==intent.revision)throw new Error("PUBLISH_INTENT_STALE");return intent;}
export async function publishIntent(draft:CreationDraftResponse,intentId:string){const result=await creationDraftRequest<CreationPublication>(`/api/creation-drafts/${draft.id}/publish`,{method:"POST",headers:{"content-type":"application/json","x-draft-csrf":draft.csrfToken},body:JSON.stringify({intentId})});updateSessionUser(result.user);finishPublishedDraft(draft.id);return result;}
export function resumePublication(id:string,intentId:string){const key=`${id}:${intentId}:${getSession()?.user.id??"anonymous"}`;const pending=resumes.get(key);if(pending)return pending;const promise=(async()=>{const draft=await creationDraftRequest<CreationDraftResponse>(`/api/creation-drafts/${id}`);await creationDraftRequest<CreationPublishIntent>(`/api/creation-drafts/${id}/publish-intents/${intentId}`);return publishIntent(draft,intentId);})();resumes.set(key,promise);promise.catch(()=>resumes.delete(key));return promise;}
