import { ru, type EventLocale } from "@event-platform/shared-types";

type Widen<T> = T extends string ? string : T extends readonly unknown[] ? { [K in keyof T]: Widen<T[K]> } : T extends object ? { [K in keyof T]: Widen<T[K]> } : T;
type EventsCopy = Widen<typeof ru.events>;

export const EVENTS_COPY: Record<EventLocale, EventsCopy> = {
  ru: ru.events,
  kk: {
    eyebrow: "Ұйымдастырушы панелі", listTitle: "Менің іс-шараларым", listDescription: "Нобайлар, жарияланған және аяқталған іс-шаралар бір тізімде.",
    create: "Іс-шара жасау", emptyTitle: "Әзірге іс-шара жоқ", emptyDescription: "Алғашқы нобайды жасаңыз. Өрістер толтырылған соң жариялауға болады.", loadFailed: "Іс-шараларды жүктеу мүмкін болмады.",
    formCreateTitle: "Жаңа іс-шара", formEditTitle: "Іс-шараны өңдеу", formDescription: "Мазмұнын, қатысу шарттарын және орын деректерін толтырыңыз.",
    wizardSteps: "Іс-шара жасау қадамдары", wizardStepLabels: ["Негізгі деректер", "Сипаттама", "Шарттар", "Төлем", "Билеттер мен зал", "Тексеру"],
    previousStep: "Артқа", saveContinue: "Сақтап, жалғастыру", autoSaving: "Өзгерістер сақталуда…", posterUploaded: "Постер жүктелді.", uploadPoster: "Постер жүктеу",
    termsHint: "Бұл шарттар тапсырыс рәсімделмей тұрып қонаққа көрсетіледі.", fullPaymentHint: "Қонақ таңдалған билет немесе үстел құнын толық төлейді.",
    saveStepFirst: "Билеттер мен залды баптау үшін алдымен негізгі деректерді сақтаңыз.", resourcesTitle: "Билеттер мен зал сызбасы", resourcesDescription: "Билет түрлері мен үстелдердің орналасуын бөлек бөлімдерде баптаңыз.", resourcesHint: "Нобай сақталған соң баптауға болады", publishedResources: "Баптаулар ұйымдастырушыға қолжетімді",
    reviewTitle: "Жариялау алдындағы тексеру", reviewHint: "Деректерді тексеріп, алдын ала қарап шығыңыз, содан кейін жариялаңыз.", preview: "Алдын ала қарау", previewNeedsSave: "Алдымен іс-шараны сақтаңыз.", previewFailed: "Алдын ала қарау жүктелмеді.", previewDraftBanner: "Алдын ала қарау — іс-шара әлі жарияланбаған", previewPublishedBanner: "Жарияланған іс-шараны алдын ала қарау", previewTickets: "билет түрі", previewTables: "үстел", previewCheckoutDisabled: "Бұл алдын ала қарау. Сатып алу әрекеттері өшірілген.",
    saved: "Өзгерістер сақталды.", created: "Нобай жасалды.", saveFailed: "Іс-шараны сақтау мүмкін болмады.", actionFailed: "Әрекетті орындау мүмкін болмады.", organizerRequired: "Бұл бет ұйымдастырушылар мен әкімшілерге арналған.", open: "Ашу", page: "Бет", of: "/", lifecycleHint: "Күй тек жариялау, бас тарту және аяқтау әрекеттерімен өзгереді.", publish: "Жариялау", complete: "Аяқтау", cancelEvent: "Іс-шарадан бас тарту", deleteDraft: "Нобайды жою", deleteConfirm: "Бұл нобайды қалпына келтіру мүмкіндігінсіз жоясыз ба?", removePoster: "Постерді жою", posterHint: "JPEG, PNG немесе WebP, 5 МБ-тан аспайды.", posterSelectedPreview: "Таңдалған файлды алдын ала қарау", posterUploadFailed: "Постерді жүктеу мүмкін болмады.", posterRemoved: "Постер жойылды.", missingPosterAlt: "Іс-шара постері",
    errors: { publishMissing: "Жариялау үшін міндетті өрістерді толтырыңыз", notFound: "Іс-шара табылмады.", invalidTransition: "Іс-шара күйін бұлай өзгертуге болмайды.", deleteNotAllowed: "Жарияланған іс-шараны біржола жоюға болмайды.", posterConflict: "Постер өзгертілді. Бетті жаңартып, қайталаңыз.", posterRequired: "Постер файлын таңдаңыз.", posterTooLarge: "Постер 5 МБ-тан аспауы керек.", posterTypeInvalid: "Постер жарамды JPEG, PNG немесе WebP файлы болуы керек.", updateEmpty: "Кемінде бір өрісті өзгертіңіз.", dateInvalid: "Жарамды күнді енгізіңіз.", timeInvalid: "Жарамды уақытты енгізіңіз.", timezoneInvalid: "Жарамды IANA уақыт белдеуін енгізіңіз.", fieldRequired: "міндетті өріс", categoryRequired: "Іс-шара санатын таңдаңыз." },
    fields: { title: "Атауы", category: "Санат", city: "Қала", date: "Күні", time: "Уақыты", timezone: "Уақыт белдеуі", ageRestriction: "Жас шектеуі", venueName: "Өтетін орны", address: "Мекенжай", announcement: "Анонс", description: "Сипаттама", program: "Бағдарлама", rules: "Ережелер", visitTerms: "Қатысу шарттары", cancellationTerms: "Бас тарту және қайтару шарттары", paymentMode: "Төлем тәсілі", showFullAmountForDeposit: "Қонаққа толық құнын ақпарат ретінде көрсету", depositTerms: "Депозит шарттары", extraConditions: "Қосымша шарттар", poster: "Постер" },
    categories: { music: "Музыка", nightlife: "Түнгі өмір", festival: "Фестиваль", comedy: "Комедия және стендап", theatre: "Театр", business: "Бизнес", education: "Білім", workshop: "Шеберлік сабағы", sport: "Спорт", family: "Отбасылық", food: "Тағам және гастрономия", other: "Басқа" },
    paymentModes: { deposit: "Депозит", full_payment: "Толық төлем" }, statuses: { draft: "Нобай", published: "Жарияланған", cancelled: "Бас тартылған", completed: "Аяқталған" },
  },
  en: {
    eyebrow: "Organizer dashboard", listTitle: "My events", listDescription: "Draft, published, and completed events in one list.",
    create: "Create event", emptyTitle: "No events yet", emptyDescription: "Create your first draft. You can publish it after completing the required fields.", loadFailed: "Could not load events.",
    formCreateTitle: "New event", formEditTitle: "Edit event", formDescription: "Add content, attendance terms, and venue details.",
    wizardSteps: "Event creation steps", wizardStepLabels: ["Basics", "Description", "Terms", "Payment", "Tickets and venue", "Review"],
    previousStep: "Back", saveContinue: "Save and continue", autoSaving: "Saving changes…", posterUploaded: "Poster uploaded.", uploadPoster: "Upload poster",
    termsHint: "Guests will see these terms before checkout.", fullPaymentHint: "Guests pay the full price of the selected ticket or table.",
    saveStepFirst: "Save the basics before setting up tickets and the venue.", resourcesTitle: "Tickets and venue map", resourcesDescription: "Set up ticket types and table placement in separate sections.", resourcesHint: "Available after saving the draft", publishedResources: "Organizer settings are available",
    reviewTitle: "Review before publishing", reviewHint: "Check the details, open a preview, and publish when ready.", preview: "Open preview", previewNeedsSave: "Save the event first.", previewFailed: "Could not load the preview.", previewDraftBanner: "Preview — this event is not published yet", previewPublishedBanner: "Preview of the published event", previewTickets: "ticket types", previewTables: "tables", previewCheckoutDisabled: "This is a preview. Purchases are disabled.",
    saved: "Changes saved.", created: "Draft created.", saveFailed: "Could not save the event.", actionFailed: "Could not complete the action.", organizerRequired: "This page is for organizers and administrators.", open: "Open", page: "Page", of: "of", lifecycleHint: "Event status changes only through publish, cancel, and complete actions.", publish: "Publish", complete: "Complete", cancelEvent: "Cancel event", deleteDraft: "Delete draft", deleteConfirm: "Delete this draft permanently?", removePoster: "Remove poster", posterHint: "JPEG, PNG, or WebP, up to 5 MB.", posterSelectedPreview: "Selected file preview", posterUploadFailed: "Could not upload the poster.", posterRemoved: "Poster removed.", missingPosterAlt: "Event poster",
    errors: { publishMissing: "Complete required fields before publishing", notFound: "Event not found.", invalidTransition: "This event status change is not allowed.", deleteNotAllowed: "A published event cannot be permanently deleted.", posterConflict: "The poster changed. Refresh and try again.", posterRequired: "Choose a poster file.", posterTooLarge: "The poster must be under 5 MB.", posterTypeInvalid: "The poster must be a valid JPEG, PNG, or WebP file.", updateEmpty: "Change at least one field.", dateInvalid: "Enter a valid date.", timeInvalid: "Enter a valid time.", timezoneInvalid: "Enter a valid IANA time zone.", fieldRequired: "required field", categoryRequired: "Choose an event category." },
    fields: { title: "Title", category: "Category", city: "City", date: "Date", time: "Time", timezone: "Time zone", ageRestriction: "Age restriction", venueName: "Venue", address: "Address", announcement: "Announcement", description: "Description", program: "Program", rules: "Rules", visitTerms: "Attendance terms", cancellationTerms: "Cancellation and refund terms", paymentMode: "Payment method", showFullAmountForDeposit: "Show full amount to guests for reference", depositTerms: "Deposit terms", extraConditions: "Additional conditions", poster: "Poster" },
    categories: { music: "Music", nightlife: "Nightlife", festival: "Festival", comedy: "Comedy and stand-up", theatre: "Theatre", business: "Business", education: "Education", workshop: "Workshop", sport: "Sports", family: "Family", food: "Food and drink", other: "Other" },
    paymentModes: { deposit: "Deposit", full_payment: "Full payment" }, statuses: { draft: "Draft", published: "Published", cancelled: "Cancelled", completed: "Completed" },
  },
};
