import { ru, type EventLocale } from "@event-platform/shared-types";
type Widen<T> = T extends string ? string : T extends object ? { [K in keyof T]: Widen<T[K]> } : T;
type GuestCopy = Widen<typeof ru.guest>;
export const GUEST_COPY: Record<EventLocale, GuestCopy> = {
  ru: ru.guest,
  kk: { myEvents: "Менің іс-шараларым", upcoming: "Алдағы", past: "Өткен", empty: "Әзірге іс-шара жоқ.", open: "Ашу", ticket: "Билет", table: "Үстел", registration: "Тіркелу күйі", countdown: "Басталуына дейін", addWallet: "Apple Wallet-ке қосу", profile: "Профиль", saveProfile: "Профильді сақтау", phone: "Телефон", email: "Электрондық пошта", saved: "Профиль сақталды.", loadFailed: "Іс-шараларды жүктеу мүмкін болмады.", walletFailed: "Билетті Apple Wallet-ке жүктеу мүмкін болмады.", states: { registered: "Тіркелген", attended: "Қатысқан", no_show: "Келмеген", cancelled: "Тоқтатылған" }, statuses: { pending: "Төлем күтілуде", confirmed: "Расталған", cancelled: "Тоқтатылған", expired: "Мерзімі өткен" }, previous: "Артқа", next: "Алға" },
  en: { myEvents: "My events", upcoming: "Upcoming", past: "Past", empty: "No events here yet.", open: "Open", ticket: "Ticket", table: "Table", registration: "Registration status", countdown: "Starts in", addWallet: "Add to Apple Wallet", profile: "Profile", saveProfile: "Save profile", phone: "Phone", email: "Email", saved: "Profile saved.", loadFailed: "Could not load events.", walletFailed: "Could not download ticket to Apple Wallet.", states: { registered: "Registered", attended: "Attended", no_show: "Did not attend", cancelled: "Cancelled" }, statuses: { pending: "Awaiting payment", confirmed: "Confirmed", cancelled: "Cancelled", expired: "Expired" }, previous: "Back", next: "Next" },
};
interface GuestExtra { openEvent: string; aboutTickets: string; pageUnavailable: string; cancelConfirm: string; refundPending: string; cancelled: string; cancel: string; failed: string; qrInvalid: string; cancellationTerms: string; loading: string; ageRestriction: string; }
export const GUEST_EXTRA: Record<EventLocale, GuestExtra> = {
  ru: { openEvent: "Открыть событие", aboutTickets: "О событии и билетах →", pageUnavailable: "Страница события больше недоступна для покупки.", cancelConfirm: "Подтверждаю отмену и ознакомился с условиями", refundPending: "Запрос на возврат создан.", cancelled: "Регистрация отменена.", cancel: "Отменить регистрацию", failed: "Не удалось выполнить действие.", qrInvalid: "QR-код недействителен.", cancellationTerms: "Условия отмены и возврата", loading: "Загрузка…", ageRestriction: "Возрастное ограничение" },
  kk: { openEvent: "Іс-шараны ашу", aboutTickets: "Іс-шара және билеттер туралы →", pageUnavailable: "Іс-шара бетінен енді билет сатып алу мүмкін емес.", cancelConfirm: "Бас тартуды растаймын және шарттармен таныстым", refundPending: "Қайтару сұрауы жасалды.", cancelled: "Тіркелу тоқтатылды.", cancel: "Тіркелуден бас тарту", failed: "Әрекетті орындау мүмкін болмады.", qrInvalid: "QR-код жарамсыз.", cancellationTerms: "Бас тарту және қайтару шарттары", loading: "Жүктелуде…", ageRestriction: "Жас шектеуі" },
  en: { openEvent: "Open event", aboutTickets: "Event and ticket details →", pageUnavailable: "This event page is no longer available for purchase.", cancelConfirm: "I confirm cancellation and have reviewed the terms", refundPending: "Refund request created.", cancelled: "Registration cancelled.", cancel: "Cancel registration", failed: "Could not complete the action.", qrInvalid: "QR code is invalid.", cancellationTerms: "Cancellation and refund terms", loading: "Loading…", ageRestriction: "Age restriction" },
};
