import type { EventLocale } from "@event-platform/shared-types";

interface StatusCopy {
  title: string; error: string; loading: string; statuses: Record<string, string>; deposit: string; full: string; approximate: string; paymentIn: string; payBefore: string; continuePayment: string; emailTickets: string; emailStatuses: Record<string, string>; resend: string; resendError: string; refresh: string; myEvents: string;
}

export const PAYMENT_STATUS_COPY: Record<EventLocale, StatusCopy> = {
  ru: { title: "Статус оплаты", error: "Не удалось получить статус оплаты.", loading: "Загрузка…", statuses: { pending: "Ожидаем оплату", paid: "Оплата подтверждена", failed: "Оплата не прошла", cancelled: "Заказ отменён", refunded: "Средства возвращены", expired: "Срок оплаты истёк", review_required: "Платёж проверяется" }, deposit: "Депозит", full: "Полная оплата", approximate: "Ориентировочно", paymentIn: "оплата в", payBefore: "Оплатите до", continuePayment: "Перейти к оплате", emailTickets: "Билеты на email", emailStatuses: { accepted: "Письмо принято почтовым провайдером; доставка во входящие не подтверждена.", queued: "Письмо ожидает отправки.", pending_payment: "Письмо отправится после подтверждения оплаты.", uncertain: "Результат отправки неизвестен.", failed: "Отправить письмо не удалось." }, resend: "Повторить отправку на тот же email", resendError: "Повторная отправка пока недоступна. Попробуйте позже.", refresh: "Обновить статус", myEvents: "Мои события" },
  kk: { title: "Төлем күйі", error: "Төлем күйін алу мүмкін болмады.", loading: "Жүктелуде…", statuses: { pending: "Төлем күтілуде", paid: "Төлем расталды", failed: "Төлем өтпеді", cancelled: "Тапсырыс тоқтатылды", refunded: "Қаражат қайтарылды", expired: "Төлем уақыты аяқталды", review_required: "Төлем тексерілуде" }, deposit: "Депозит", full: "Толық төлем", approximate: "Шамамен", paymentIn: "төлем валютасы", payBefore: "Дейін төлеңіз:", continuePayment: "Төлемге өту", emailTickets: "Email билеттері", emailStatuses: { accepted: "Пошта провайдері хатты қабылдады; кіріс жәшігіне жеткізілгені расталмаған.", queued: "Хат жіберілуін күтуде.", pending_payment: "Хат төлем расталған соң жіберіледі.", uncertain: "Жіберу нәтижесі белгісіз.", failed: "Хатты жіберу мүмкін болмады." }, resend: "Сол email мекенжайына қайта жіберу", resendError: "Қайта жіберу әзірше қолжетімсіз. Кейінірек қайталаңыз.", refresh: "Күйді жаңарту", myEvents: "Менің іс-шараларым" },
  en: { title: "Payment status", error: "Could not get the payment status.", loading: "Loading…", statuses: { pending: "Awaiting payment", paid: "Payment confirmed", failed: "Payment failed", cancelled: "Order cancelled", refunded: "Funds refunded", expired: "Payment expired", review_required: "Payment under review" }, deposit: "Deposit", full: "Full payment", approximate: "Approximately", paymentIn: "payment in", payBefore: "Pay before", continuePayment: "Proceed to payment", emailTickets: "Tickets by email", emailStatuses: { accepted: "The email provider accepted the message; inbox delivery is unconfirmed.", queued: "Email is queued for sending.", pending_payment: "Email will be sent after payment confirmation.", uncertain: "Sending outcome is unknown.", failed: "Could not send the email." }, resend: "Resend to the same email", resendError: "Resending is unavailable right now. Try again later.", refresh: "Refresh status", myEvents: "My events" },
};
