import { quickRu, type EventLocale } from "@event-platform/shared-types";

type Widen<T> = T extends string ? string : T extends object ? { [K in keyof T]: Widen<T[K]> } : T;
type QuickCopy = Widen<typeof quickRu>;
export const QUICK_COPY: Record<EventLocale, QuickCopy> = {
  ru: quickRu,
  kk: {
    title: "Тіркелмей сатып алу", name: "Атыңыз", start: "Telegram арқылы жалғастыру", verify: "Telegram растау", check: "Растадым — тексеру", verified: "Telegram расталды", checkout: "Төлемге өту", accept: "Бас тарту және депозит шарттарын қабылдаймын", error: "Әрекетті орындау мүмкін болмады. Деректерді тексеріп, қайталаңыз.", saved: "Сатып алу жеке кабинетте сақталды", claim: "Сатып алуды аккаунтыма сақтау", login: "Telegram арқылы кіріп, сатып алуды сақтау", refresh: "Күйді жаңарту", qr: "QR-кодты ашу", wallet: "Apple Wallet-ке қосу", payment: "Төлем", full: "Толық төлем", deposit: "Депозит", waiting: "Ботты ашып, билеттерді алуды растаңыз. Сайтта аккаунт жасалмайды.", return: "Төлемнен кейін осы бетке оралыңыз.", unavailable: "Сатып алу қолжетімсіз. Тапсырыс жасаған браузерде ашыңыз.", quick: "Тіркелмей сатып алу", purchases: "Сатып алулар", quantity: "Саны", seats: "орын", recipientPending: "Растау әлі алынбады. Ботта Start басып, қайта тексеріңіз.", informationalFull: "Толық құн (ақпарат үшін)", botPending: "Сатып алуды қабылдау расталуда. Төлемнен кейін билет немесе бронь осында шығады.", botVerified: "Telegram расталды. Төлем үшін сайтқа оралыңыз — тіркелу қажет емес.", ticketStatuses: { created: "Жасалды", pending_payment: "Төлем күтілуде", paid: "Төленді", active: "Белсенді", used: "Пайдаланылды", cancelled: "Тоқтатылды", refunded: "Қайтарылды" }
  },
  en: {
    title: "Buy without registering", name: "Your name", start: "Continue with Telegram", verify: "Verify Telegram", check: "I've verified — check", verified: "Telegram verified", checkout: "Proceed to payment", accept: "I accept the cancellation and deposit terms", error: "Could not complete the action. Check the details and try again.", saved: "Purchase saved to your account", claim: "Save purchase to my account", login: "Sign in with Telegram to save purchase", refresh: "Refresh status", qr: "Open QR code", wallet: "Add to Apple Wallet", payment: "Payment", full: "Full payment", deposit: "Deposit", waiting: "Open the bot and confirm ticket delivery. No website account is created.", return: "Return to this page after payment.", unavailable: "Purchase unavailable. Open it in the browser used for checkout.", quick: "Buy without registering", purchases: "Purchases", quantity: "Quantity", seats: "seats", recipientPending: "Confirmation has not arrived. Press Start in the bot, then check again.", informationalFull: "Full price (for reference)", botPending: "Confirming purchase delivery. Your ticket or booking will appear here after payment.", botVerified: "Telegram verified. Return to the site to pay — no registration is needed.", ticketStatuses: { created: "Created", pending_payment: "Awaiting payment", paid: "Paid", active: "Active", used: "Used", cancelled: "Cancelled", refunded: "Refunded" }
  },
};

interface QuickExtra { choiceUnavailable: string; back: string; loading: string; venueLayout: string; yourChoice: string; unavailableTicket: string; table: string; wholeTable: string; unavailableSeat: string; total: string; approximate: string; paymentIn: string; combinedRefund: string; selectionChanged: string; tickets: string; tables: string; places: string; choices: string; seat: string; selectedSeats: string; row: string; seatsUnavailable: string; seatSelectionChanged: string; backToMap: string; cancellationTerms: string; depositTerms: string; continueGuest: string; recipientVerified: string; verifyRecipient: string; fullPriceRemainder: string; validUntil: string; emailTickets: string; status: string; deliveryConfirmed: string; deliveryPending: string; loginVerified: string; walletFailed: string; myTickets: string; }
export const QUICK_EXTRA: Record<EventLocale, QuickExtra> = {
  ru: { choiceUnavailable: "Выбранный билет или стол больше недоступен. Выберите другой вариант.", back: "Назад", loading: "Загрузка…", venueLayout: "Схема зала и доступность столов", yourChoice: "Ваш выбор", unavailableTicket: "Недоступный билет", table: "Стол", wholeTable: "целиком", unavailableSeat: "Недоступное место", total: "Итого к оплате", approximate: "Ориентировочно", paymentIn: "оплата в", combinedRefund: "Для комбинированного заказа возврат оформляется целиком через организатора.", selectionChanged: "Часть выбранного больше недоступна или использует другую валюту. Вернитесь к схеме и обновите выбор.", tickets: "Билеты", tables: "Столы", places: "места", choices: "Билеты, столы или места", seat: "место", selectedSeats: "Выбранные места", row: "Ряд", seatsUnavailable: "Места больше недоступны", seatSelectionChanged: "Часть мест больше недоступна или имеет другую валюту. Вернитесь к схеме и выберите места заново.", backToMap: "Вернуться к схеме", cancellationTerms: "Условия отмены и возврата", depositTerms: "Условия депозита", continueGuest: "Продолжить без регистрации", recipientVerified: "Получатель подтверждён", verifyRecipient: "Подтвердите Telegram или email для получения билетов", fullPriceRemainder: "Остаток оплачивается по условиям организатора.", validUntil: "Заказ действителен до", emailTickets: "Email для билетов", status: "Статус", deliveryConfirmed: "Telegram принял отправку билетов. Просмотр сообщения гостем не подтверждается.", deliveryPending: "Билеты доступны здесь. Отправка в Telegram ещё выполняется.", loginVerified: "Войти через подтверждённый email или телефон", walletFailed: "Не удалось скачать билет в Apple Wallet.", myTickets: "Мои билеты" },
  kk: { choiceUnavailable: "Таңдалған билет немесе үстел енді қолжетімсіз. Басқа нұсқаны таңдаңыз.", back: "Артқа", loading: "Жүктелуде…", venueLayout: "Зал сызбасы және үстелдердің қолжетімділігі", yourChoice: "Сіздің таңдауыңыз", unavailableTicket: "Қолжетімсіз билет", table: "Үстел", wholeTable: "толығымен", unavailableSeat: "Қолжетімсіз орын", total: "Төленетін сома", approximate: "Шамамен", paymentIn: "төлем валютасы", combinedRefund: "Аралас тапсырыстың қайтарымы ұйымдастырушы арқылы толық рәсімделеді.", selectionChanged: "Таңдалған нұсқаның бір бөлігі қолжетімсіз немесе валютасы бөлек. Сызбаға оралып, таңдауды жаңартыңыз.", tickets: "Билеттер", tables: "Үстелдер", places: "орындар", choices: "Билеттер, үстелдер немесе орындар", seat: "орын", selectedSeats: "Таңдалған орындар", row: "Қатар", seatsUnavailable: "Орындар қолжетімсіз", seatSelectionChanged: "Кейбір орындар қолжетімсіз немесе валютасы бөлек. Сызбаға оралып, қайта таңдаңыз.", backToMap: "Сызбаға оралу", cancellationTerms: "Бас тарту және қайтару шарттары", depositTerms: "Депозит шарттары", continueGuest: "Тіркелмей жалғастыру", recipientVerified: "Алушы расталды", verifyRecipient: "Билеттерді алу үшін Telegram немесе email растаңыз", fullPriceRemainder: "Қалған сома ұйымдастырушы шарттары бойынша төленеді.", validUntil: "Тапсырыс жарамды мерзім", emailTickets: "Билеттер email мекенжайы", status: "Күйі", deliveryConfirmed: "Telegram билеттерді қабылдады. Қонақ хабарды қарағаны расталмаған.", deliveryPending: "Билеттер осы жерде қолжетімді. Telegram-ға жіберу жалғасуда.", loginVerified: "Расталған email немесе телефон арқылы кіру", walletFailed: "Билетті Apple Wallet-ке жүктеу мүмкін болмады.", myTickets: "Менің билеттерім" },
  en: { choiceUnavailable: "The selected ticket or table is no longer available. Choose another option.", back: "Back", loading: "Loading…", venueLayout: "Venue map and table availability", yourChoice: "Your selection", unavailableTicket: "Unavailable ticket", table: "Table", wholeTable: "whole table", unavailableSeat: "Unavailable seat", total: "Total due", approximate: "Approximately", paymentIn: "payment in", combinedRefund: "Refunds for combined orders are processed in full through the organizer.", selectionChanged: "Part of your selection is unavailable or uses a different currency. Return to the map and update it.", tickets: "Tickets", tables: "Tables", places: "seats", choices: "Tickets, tables, or seats", seat: "seat", selectedSeats: "Selected seats", row: "Row", seatsUnavailable: "Seats are no longer available", seatSelectionChanged: "Some seats are unavailable or use a different currency. Return to the map and choose again.", backToMap: "Return to map", cancellationTerms: "Cancellation and refund terms", depositTerms: "Deposit terms", continueGuest: "Continue without registering", recipientVerified: "Recipient verified", verifyRecipient: "Verify Telegram or email to receive tickets", fullPriceRemainder: "The balance is paid according to the organizer's terms.", validUntil: "Order valid until", emailTickets: "Ticket email", status: "Status", deliveryConfirmed: "Telegram accepted the tickets. The guest viewing the message is unconfirmed.", deliveryPending: "Tickets are available here. Sending to Telegram is still in progress.", loginVerified: "Sign in with verified email or phone", walletFailed: "Could not download the ticket to Apple Wallet.", myTickets: "My tickets" },
};
